In [1]:
import os

os.chdir("..")

Data Structures
===============

The previous chapter introduced Python, providing enough background to do
simple computations on data sets. This chapter focuses on the foundational
knowledge and skills you'll need to use Python effectively in the long term.
Specifically, it begins with a deep dive into data structures and data types in
Python and Pandas. Then, it explains how to use this knowledge during data
analysis.

:::{admonition} Learning Objectives
* Create lists, arrays, and Pandas Series
* Check the type and class of an object
* Coerce an object into a different type
* Describe and differentiate `None`, `NA`, and `NaN`
* Index sequences with empty, integer, string, and logical arguments
* Negate or combine conditions with logic operations
* Subset Series objects and DataFrames
* Find and remove missing values in a DataFrame and Series
:::


Getting Started
---------------

### Packages

We will be working with two packages in this chapter, NumPy and Pandas. Start
by using what you learned in {numref}`modules` to load these packages with
their conventional aliases.

In [2]:
import numpy as np
import pandas as pd

### Loading Data

In the last chapter, you used Pandas to load tabular data into Python.

In [3]:
banknotes = pd.read_csv("data/banknotes.csv")

Recall that you can select a single column with bracket notation. For the next
little while, you will be working with the `current_bill_value` column. Select
it and assign it to a variable.

In [4]:
bill_value = banknotes["current_bill_value"]

(arrays-lists-sequences)=
Arrays, Lists, and Other Sequences
----------------------------------

(pandas-series)=
### Pandas Series

Now examine the variable you created.

In [5]:
bill_value

0      100
1      100
2       50
3       20
4       10
      ...
274     10
275     20
276     50
277    100
278    200
Name: current_bill_value, Length: 279, dtype: int64

You may notice that the data looks a little different from how it displays in a
DataFrame. This is a visual clue: instead of being its own DataFrame,
`bill_value` is a Pandas **Series**. Series objects in Pandas are
one-dimensional **arrays**, data elements stored in an ordered sequence. They
also contain additional metadata and a lot of extra functionality. As you will
learn in this chapter, both a Series and a DataFrame allow you to:
* summarize data
* handle missing data
* reshape and transform data
* subset and filter data
* merge and combine data

Here are a few examples of the extra metadata a Series contains (more on this
later):

In [6]:
bill_value.name

'current_bill_value'

In [7]:
bill_value.shape

(279,)

(lists)=
### Lists

In actuality, a Series is just one kind of sequence object available to you in
Python. The most common such object is a **list**. A list is a container for
zero or more values. Its values are called **elements**, and its **length** is
the number of elements it contains. Like a Series, a list is ordered, so it has
a first element, second element, and so on up to the length of the list.

You can make a list by enclosing comma-separated values in square brackets
`[]`, like this:

In [8]:
[1, 2, 3]

[1, 2, 3]

Lists can be empty:

In [9]:
[]

[]

You can also convert certain objects to lists with `list`:

In [10]:
list(bill_value)

[100,
 100,
 50,
 20,
 10,
 50,
 10,
 20,
 10,
 50,
 100,
 100,
 20,
 5,
 20,
 1000,
 500,
 200,
 100,
 50,
 10,
 5,
 2,
 50,
 50,
 10,
 100,
 200,
 100,
 50,
 10,
 10,
 20,
 200,
 20,
 200,
 100,
 20,
 5,
 50,
 100,
 10,
 10,
 10,
 10,
 10,
 20,
 5000,
 1000,
 10000,
 20000,
 2000,
 50000,
 20000,
 2000,
 10000,
 100000,
 1000,
 20000,
 5000,
 50000,
 2000,
 10000,
 10000,
 5000,
 20000,
 50000,
 2000,
 1000,
 2000,
 5000,
 1000,
 200,
 500,
 5000,
 2000,
 1000,
 500,
 200,
 100,
 200,
 200,
 200,
 500,
 2000,
 100,
 2000,
 100,
 100,
 20,
 500,
 5,
 50,
 20,
 10,
 5,
 10,
 20,
 50,
 5,
 2,
 200,
 1,
 10,
 20,
 50,
 100,
 500,
 100000,
 5000,
 100000,
 10000,
 50000,
 20000,
 50000,
 20000,
 2000,
 1000,
 2000,
 10000,
 200,
 100,
 50,
 20,
 2000,
 500,
 10000,
 5000,
 1000,
 500,
 1000,
 100,
 50,
 500,
 1000,
 10000,
 5000,
 5000,
 500,
 200,
 20,
 100,
 50,
 1000,
 5000,
 1000,
 50000,
 10000,
 1000,
 200,
 20,
 50,
 500,
 2000,
 100,
 500,
 500,
 1000,
 1000,
 1000,
 500,
 20,
 200,
 200,
 100,
 100,
 20,
 500,
 1000,
 10,
 100,
 5,
 20,
 200,
 1000,
 5,
 50,
 100,
 10,
 20,
 100,
 20,
 10,
 10,
 50,
 100,
 200,
 50,
 500,
 100,
 500,
 200,
 20,
 50,
 1000,
 1000,
 1000,
 1,
 5,
 10,
 20,
 50,
 100,
 5000,
 2000,
 100,
 1000,
 500,
 200,
 50,
 10,
 20,
 200,
 500,
 20,
 100,
 50,
 1000,
 100000,
 200,
 500,
 1000,
 5000,
 10000,
 20000,
 50000,
 10,
 20,
 10,
 5,
 5,
 10,
 20,
 50,
 100,
 200,
 10,
 5,
 50,
 20,
 100,
 200,
 50,
 1000,
 20,
 200,
 100,
 500,
 10,
 5,
 2,
 1,
 50,
 2,
 5,
 1,
 20,
 100,
 10,
 1000,
 100,
 20,
 500,
 200,
 50,
 2000,
 500,
 50,
 2,
 200,
 20,
 100,
 10,
 5,
 10,
 20,
 50,
 100,
 200]

Unlike a Series, which is built on top of NumPy arrays, the elements of a list
can be qualitatively different. For instance, this list contains a number,
string, and another list (with one element):

In [11]:
l = [8, "hello", [4.2]]
l

[8, 'hello', [4.2]]

You can get the length of a list with the built-in `len` function:

In [12]:
len(l)

3

(indexing)=
### Indexing

Square brackets `[]` also serve as the **indexing operator** in Python. The
indexing operator gets or sets an element of a list based on the element's
position. Python uses **zero-based indexing**, which means the first element of
a data structure is at position 0. The code to get the first element of the
list `l` is:

In [13]:
l[0]

8

Likewise, getting the third element is:

In [14]:
l[2]

[4.2]

The above logic extends to sequences stored inside sequences. Below, we get the
value  stored in the sublist of `l`.

In [15]:
l[2][0]

4.2

You can set the element of a list by assigning a value at that index. So the
code to change the first element of `l` to the string "hi" is:

In [16]:
l[0] = "hi"
l

['hi', 'hello', [4.2]]

(references)=
### References

Assigning values to a list by its index positions is not without complication.
Suppose you assign a list to a variable `x` and then create a new variable,
`y`, from `x`. If you change an element of `y`, it will also change `x`:

In [17]:
x = [1, 2]
y = x
y[0] = 10
x

[10, 2]

This happens because of the way Python handles variables. In Python, variables
point, or **refer**, to a location in your computer's memory. New variables
created from the same data continue to point to that data unless directed
otherwise, and thus operations on separate variables, or **references** can
affect the same data.

The same holds true for Pandas objects. The variable `bill_value` is only a
reference to a portion of the data `banknotes` represents.

We take a **copy** of objects to create a new reference when assigning
variables:

In [18]:
x = [1, 2]
y = x.copy()
y[0] = 10
x

[1, 2]

You can also convert your list to a **tuple** to prevent problems with value
assignments. Tuples operate similarly to lists, but they are **immutable**.
That is, once you create one, you cannot alter it.

In [19]:
x = [1, 2]
y = x
x = tuple(x)
y[0] = 10
x

(1, 2)

To check what kind of object, or **class**, a variable represents, use the
built-in `type` function.

In [20]:
type(y)

list

In [21]:
type(x)

tuple

In [22]:
type(bill_value)

pandas.core.series.Series

(data-types)=
Data Types
----------

Recall that a list can contain qualitatively different objects, whereas a
Series cannot. What happens, then, if you were to convert `l` into a Series?

In [23]:
pd.Series(l)

0       hi
1    hello
2    [4.2]
dtype: object

Notice that the `dtype` value, which applies to all values in the Series, is
`object`. This is a Pandas catchall for columns with mixed data types and for
ones with strings. Why did converting `l` to a Series change the data type?

To answer this, you need to know about how Python handles different types of
data, including numeric and non-numeric data. You already caught a glimpse of
these data types in {numref}`summarizing-data`, when you used `info` to inspect
a DataFrame. Types are listed in the `Dtype` column.

In [24]:
banknotes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   currency_code          279 non-null    object
 1   country                279 non-null    object
 2   currency_name          279 non-null    object
 3   name                   279 non-null    object
 4   gender                 279 non-null    object
 5   bill_count             279 non-null    float64
 6   profession             279 non-null    object
 7   known_for_being_first  279 non-null    object
 8   current_bill_value     279 non-null    int64
 9   prop_total_bills       59 non-null     float64
 10  first_appearance_year  279 non-null    int64
 11  death_year             272 non-null    object
 12  comments               119 non-null    object
 13  hover_text             89 non-null     object
 14  has_portrait           279 non-null    bool
 15  id                     279 non-null    object
 16  scaled_bill_value      278 non-null    float64
dtypes: bool(1), float64(3), int64(2), object(11)
memory usage: 35.3+ KB

Some of these types are built into Python, while others are specific to Pandas.
Pandas does more work than Python to ensure consistency and specificity across
data types. This is because Pandas is built around NumPy, which provides more
control to the programmer by adding extra data types to best match programming
tasks. This also comes with improved memory and time performance.

A list of data types that you will often encounter in data analysis is below.
Entries marked with \* are NumPy/Pandas extensions to base Python types.
* Boolean
* Integer
* Float
* String
* Complex
* Datetime\*
* Time Delta\*
* StringDtype\*
* Object\*


(numeric-types)=
### Numeric Types

From `banknotes.info()` we learn that `current_bill_value` has an `int64` type.
Integers are one of the two ways that Python stores numeric data. When storing
whole numbers, such as 0, 3, 3000, etc., Python uses integers

The `64` part is an add-on from Pandas. Here, `64` refers to the number of bits
used to store the data, which in turn affects the range of numbers a variable
can hold. Normally though, Python just records the `int`, as in the case below,
where we use `type` to identify a data type:

In [25]:
type(4)

int

Typically, `int` numbers are 32 bits.

Why is bit size important? Consider the fact that a 64-bit integer can hold
values between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807,
whereas a 16-bit integer covers everything between -32,768 and 32,767. Knowing
this information really matters when you're working with large numbers. Without
that knowledge, you might assign 32,768 to an `int16` variable and find that
you've caused an **overflow** error.

The same holds for instances where you need a certain amount of precision in
your data. For example, Python and NumPy have the ability to represent
irrational numbers, like pi. Ultimately, your computer has to represent such
numbers with decimal values, so the number of decimal places a variable can
hold will affect what pi "means" in your code:

In [26]:
np.pi

3.141592653589793

The above is an example of a `float` (for floating point number) type. Use this
when you need decimal precision of any kind:

In [27]:
banknotes["bill_count"]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
274    1.0
275    1.0
276    1.0
277    1.0
278    1.0
Name: bill_count, Length: 279, dtype: float64

You can explicitly construct both numeric data types in Python. Here is an
integer:

In [28]:
n = int(4)

Importantly, this doesn't allow for decimal points:

In [29]:
n = int(4.67)
n

4

The `float` constructor will, however:

In [30]:
n = float(4.67)
n

4.67

Though `int` won't accept a decimal, you can perform arithmetic operations
across numeric types. For example, multiply `current_bill_value` by one and a
half times its current value:

In [31]:
bill_value * 1.5

0      150.0
1      150.0
2       75.0
3       30.0
4       15.0
       ...
274     15.0
275     30.0
276     75.0
277    150.0
278    300.0
Name: current_bill_value, Length: 279, dtype: float64

Notice that the `dtype` has changed from `int64` to `float64`. Python does this
automatically, converting the more limited data type to match the more complex
one. In this case, that means converting integers, which can't hold decimals,
to floats, which can.


(booleans)=
### Booleans

The most limited data type is `bool`, or a Boolean. It is a logical value that
stores either True or False. Booleans are commonly used for expressions with
yes-or-no responses, or for storing the state of your code.

In [32]:
banknotes["has_portrait"]

0      True
1      True
2      True
3      True
4      True
       ...
274    True
275    True
276    True
277    True
278    True
Name: has_portrait, Length: 279, dtype: bool

In [33]:
coded_in_java = False
type(coded_in_java)

bool

(strings)=
### Strings

String objects, or `str`, are the most complex data type. They have the most
attributes and methods associated with them, and they also take up the most
amount of memory.

Use double `"` or single `'` quotes to construct a string:

In [34]:
"Hello, world!"

'Hello, world!'

Back in Pandas, strings are stored under the `object` data type. Look at the
`dtype` readout below.

In [35]:
banknotes["name"]

0                       Eva Perón
1            Julio Argentino Roca
2      Domingo Faustino Sarmiento
3            Juan Manuel de Rosas
4                 Manuel Belgrano
                  ...
274                Nelson Mandela
275                Nelson Mandela
276                Nelson Mandela
277                Nelson Mandela
278                Nelson Mandela
Name: name, Length: 279, dtype: object

Alternatively, use the `dtype` attribute of a Series:

In [36]:
banknotes["name"].dtype

dtype('O')

Pandas uses this special data type because strings aren't fixed-length
sequences, like numbers are. So Pandas has to build in the possibility that a
string will become shorter or longer.


(coercion-and-conversion)=
### Coercion and Conversion

Since arrays like a Series have to contain the same data type throughout,
Pandas will automatically convert all elements in a Series to an `object` when
even just one element is a string. This is known as implicit **type coercion**.
It's why all the components of the list `l` became `objects`.

You've actually seen a few examples of this already. Multiplying the `int64`
Series `bill_value` by the `float` 1.5 produced `float` numbers. The same holds
for:

In [37]:
8 / 0.25

32.0

And:

In [38]:
True + 2

3

In the above, Python converts `True` to `1` and then performs the arithmetic.

**Type conversion** is when you change an object's data type in an explicit
manner.

In [39]:
b = int(4.5)
b

4

...is the example you saw earlier. Here is another:

In [40]:
bool(0)

False

And one more:

In [41]:
str(105)

'105'

Python can even read strings like numbers and Boolean values:

In [42]:
float("7.3")

7.3

In [43]:
bool("True")

True

Note however that such operations have to be logically sound. This will not
work:

In [44]:
int("Hello world!")

ValueError: invalid literal for int() with base 10: 'Hello world!'

(comparison-operators)=
### Comparison Operators

Programming tasks often involve comparing variables. Use **comparison
operators** to do so.

| Symbol | Meaning                  |
| :----: | :----------------------- |
| `<`    | less than                |
| `>`    | greater than             |
| `<=`   | less than or equal to    |
| `>=`   | greater than or equal to |
| `==`   | equal to                 |
| `!=`   | not equal to             |

Notice that the "equal to" operator is two equal signs. This is to distinguish
it from the assignment `=` operator.

In [45]:
sum(bill_value) < 10000

False

In [46]:
bill_value == banknotes["current_bill_value"]

0      True
1      True
2      True
3      True
4      True
       ...
274    True
275    True
276    True
277    True
278    True
Name: current_bill_value, Length: 279, dtype: bool

In [47]:
bill_value % 25 != 0

0      False
1      False
2      False
3       True
4       True
       ...
274     True
275     True
276    False
277    False
278    False
Name: current_bill_value, Length: 279, dtype: bool

(indexing-in-pandas)=
Indexing in Pandas
------------------

In the last cell above, the readout values change depending on the underlying
data. If you want to inspect that data more closely, you can index the Series.
Conceptually, indexing a Series is very similar to indexing a list or tuple,
but Pandas offers additional ways to select and subset data via indexes.


(the-pandas-index)=
### What's an Index?

It can do so because a Pandas index is more than just a positional location.
Indexes serve three important roles:

1. As metadata to provide additional context about a data set
2. As a way to explicitly and automatically align data
3. As a convenience for getting and setting subsets of data

The index of a series is available via the `index` attribute:

In [48]:
bill_value.index

RangeIndex(start=0, stop=279, step=1)

Index labels can be numbers, strings, dates, or other values. Pandas provides
subclasses of `Index` for specific purposes, which you can read more about
[here][].

[here]: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html

Indexes, like tuples, are **immutable**. Each of its labels cannot be changed.
But every index also has a name, and you can change this.

In [49]:
bill_value.name = "bill_value"
bill_value

0      100
1      100
2       50
3       20
4       10
      ...
274     10
275     20
276     50
277    100
278    200
Name: bill_value, Length: 279, dtype: int64

The above also applies to DataFrames.

In [50]:
banknotes.index

RangeIndex(start=0, stop=279, step=1)

Oftentimes, an index is a range of numbers. But this can be changed. The code
below uses the `set_index` method to change the index of `banknotes` to
`country`. We use `inplace` to make this change without having to reassign the
result

In [51]:
banknotes.set_index("country", inplace=True)
banknotes.index

Index(['Argentina', 'Argentina', 'Argentina', 'Argentina', 'Argentina',
       'Australia', 'Australia', 'Australia', 'Australia', 'Australia',
       ...
       'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela',
       'South Africa', 'South Africa', 'South Africa', 'South Africa',
       'South Africa'],
      dtype='object', name='country', length=279)

(indexing-by-position)=
### Indexing by Position

Changing the index affects how you select elements. There are three main
methods for accessing specific values in Pandas:
1. By integer position
2. By label/name
3. By a condition

To access elements in a series by integer position, use `iloc`:

In [52]:
bill_value.iloc[5]

50

Using `iloc` is extensible to sequences of values:

In [53]:
bill_value.iloc[[5, 15, 25, 35]]

5       50
15    1000
25      10
35     200
Name: bill_value, dtype: int64

Use a **slice** to select a range of elements. The syntax for a slice is
`start:stop:step`, with the second colon `:` and arguments being optional. This
syntax also applies to lists.

In [54]:
bill_value.iloc[0:5]

0    100
1    100
2     50
3     20
4     10
Name: bill_value, dtype: int64

Below, we use a slice to get every twentieth element in the Series:

In [55]:
bill_value.iloc[::20]

0        100
20        10
40       100
60     50000
80       200
100        2
120      200
140       20
160      500
180      100
200       20
220      500
240      100
260      100
Name: bill_value, dtype: int64

Slices also accept negative values. This counts back from the end of a
sequence.

In [56]:
bill_value.iloc[-5:]

274     10
275     20
276     50
277    100
278    200
Name: bill_value, dtype: int64

That makes the above output the same as the output below:

In [57]:
bill_value.tail()

274     10
275     20
276     50
277    100
278    200
Name: bill_value, dtype: int64

(indexing-by-label)=
### Indexing by Label

Use `loc` to index a Series or DataFrame by label.

In [58]:
banknotes.loc["Peru"]

,currency_code,currency_name,name,gender,bill_count,profession,known_for_being_first,current_bill_value,prop_total_bills,first_appearance_year,death_year,comments,hover_text,has_portrait,id,scaled_bill_value
country,,,,,,,,,,,,,,,,
Peru,PEN,Sol,Jorge Basadre Grohmann,M,1.0,Politician,No,100,NaN,1991,1980,NaN,NaN,False,PEN_Basadre,0.473684
Peru,PEN,Sol,Raúl Porras Barrenechea,M,1.0,Politician,No,20,NaN,1991,1960,NaN,NaN,False,PEN_Raul,0.052632
Peru,PEN,Sol,María Isabel Granda y Larco,F,1.0,Musician,No,10,NaN,2021,1983,NaN,NaN,False,PEN_Granda,0.000000
Peru,PEN,Sol,José Abelardo Quiñones Gonzales,M,1.0,Military,No,10,NaN,1991,1941,NaN,NaN,False,PEN_Abelardo,0.000000
Peru,PEN,Sol,Abraham Valdelomar Pinto,M,1.0,Writer,No,50,NaN,1991,1919,NaN,NaN,False,PEN_Pinto,0.210526
Peru,PEN,Sol,Pedro Paulet,M,1.0,STEM,Yes,100,NaN,2021,1945,Alleged first person to build a liquid-propell...,Alleged first person to build a liquid-propell...,False,PEN_Paulet,0.473684
Peru,PEN,Sol,Santa Rosa de Lima,F,1.0,Religious figure,Yes,200,NaN,1995,1617,First catholic saint of the Americas,First Catholic saint of the Americas,False,PEN_Santa,1.000000

You can select specific columns as well:

In [59]:
banknotes.loc["Peru", "name"]

country
Peru             Jorge Basadre Grohmann
Peru            Raúl Porras Barrenechea
Peru        María Isabel Granda y Larco
Peru    José Abelardo Quiñones Gonzales
Peru           Abraham Valdelomar Pinto
Peru                       Pedro Paulet
Peru                 Santa Rosa de Lima
Name: name, dtype: object

Just as with `iloc`, it's possible to feed sequences into `loc`:

In [60]:
banknotes.loc[["Peru", "Serbia", "Ukraine"]]

,currency_code,currency_name,name,gender,bill_count,profession,known_for_being_first,current_bill_value,prop_total_bills,first_appearance_year,death_year,comments,hover_text,has_portrait,id,scaled_bill_value
country,,,,,,,,,,,,,,,,
Peru,PEN,Sol,Jorge Basadre Grohmann,M,1.0,Politician,No,100,NaN,1991,1980,NaN,NaN,False,PEN_Basadre,0.473684
Peru,PEN,Sol,Raúl Porras Barrenechea,M,1.0,Politician,No,20,NaN,1991,1960,NaN,NaN,False,PEN_Raul,0.052632
Peru,PEN,Sol,María Isabel Granda y Larco,F,1.0,Musician,No,10,NaN,2021,1983,NaN,NaN,False,PEN_Granda,0.000000
Peru,PEN,Sol,José Abelardo Quiñones Gonzales,M,1.0,Military,No,10,NaN,1991,1941,NaN,NaN,False,PEN_Abelardo,0.000000
Peru,PEN,Sol,Abraham Valdelomar Pinto,M,1.0,Writer,No,50,NaN,1991,1919,NaN,NaN,False,PEN_Pinto,0.210526
Peru,PEN,Sol,Pedro Paulet,M,1.0,STEM,Yes,100,NaN,2021,1945,Alleged first person to build a liquid-propell...,Alleged first person to build a liquid-propell...,False,PEN_Paulet,0.473684
Peru,PEN,Sol,Santa Rosa de Lima,F,1.0,Religious figure,Yes,200,NaN,1995,1617,First catholic saint of the Americas,First Catholic saint of the Americas,False,PEN_Santa,1.000000
Serbia,RSD,Serbian dinar,Slobodan Jovanovic,M,1.0,Head of Gov't,No,5000,NaN,2003,1958,"writer, politician, diplomat and prime ministe...",NaN,True,RSD_Slobodan,1.000000
Serbia,RSD,Serbian dinar,Milutin Milanković,M,1.0,STEM,No,2000,NaN,2011,1958,NaN,NaN,True,RSD_Milutin,0.398798
Serbia,RSD,Serbian dinar,Nikola Tesla,M,1.0,STEM,No,100,NaN,2003,1943,NaN,NaN,True,RSD_Tesla,0.018036
Serbia,RSD,Serbian dinar,Dorde Vajfert,M,1.0,Other,No,1000,NaN,2003,1937,was governer of the national Bank of Serbia. e...,NaN,True,RSD_Dorde,0.198397
Serbia,RSD,Serbian dinar,Jovan Cvijic,M,1.0,STEM,No,500,NaN,2004,1927,NaN,NaN,True,RSD_Cvijic,0.098196
Serbia,RSD,Serbian dinar,Nadežda Petrović,F,1.0,Visual Artist,No,200,NaN,2005,1915,NaN,NaN,True,RSD_Petrovic,0.038076
Serbia,RSD,Serbian dinar,Stevan Stevanovic Mokranjac,M,1.0,Musician,Yes,50,NaN,2005,1914,Composer. was part of Serbia's first string qu...,Member of Serbia's first string quartet,True,RSD_Stevanovic,0.008016
Serbia,RSD,Serbian dinar,Vuk Stefanovic Karadžic,M,1.0,Writer,Yes,10,NaN,2006,1864,wrote the 1st dictionary in the reformed Serbi...,Wrote the first dictionary in the reformed Ser...,True,RSD_Vuk,0.000000
Serbia,RSD,Serbian dinar,Petar Petrovic Njegoš,M,1.0,Writer,No,20,NaN,2006,1851,wrote some of the most imporant Serbian litera...,NaN,True,RSD_Njegos,0.002004
Ukraine,UAH,hryvna,Mykhailo Hrusheskyi,M,1.0,Politician,No,50,NaN,1992,1934,"also an author, president of Central Rada (Sov...",NaN,False,UAH_Mykhailo,0.049049
Ukraine,UAH,hryvna,Volodymyr Vernadskyi,M,1.0,STEM,No,1000,NaN,2019,1945,NaN,NaN,False,UAH_Vernadskyi,1.000000
Ukraine,UAH,hryvna,Ivan Franko,M,1.0,Writer,Yes,20,NaN,1992,1916,1st author of detective novels and modern poet...,First author of detective novels and modern po...,False,UAH_Franko,0.019019
Ukraine,UAH,hryvna,Lesya Ukrainka,F,1.0,Writer,No,200,NaN,2001,1913,NaN,NaN,False,UAH_Ukrainka,0.199199
Ukraine,UAH,hryvna,Taras Shevchenko,M,1.0,Writer,No,100,NaN,1992,1841,NaN,NaN,False,UAH_Taras,0.099099
Ukraine,UAH,hryvna,Hryhoriy Skovoroda,M,1.0,Writer,No,500,NaN,2006,1794,NaN,NaN,False,UAH_Skovoroda,0.499499
Ukraine,UAH,hryvna,Ivan Mazepa,M,1.0,Head of Gov't,No,10,NaN,1992,1709,"elected ""Hetman of Zaporizhian Host"" . also se...",NaN,False,UAH_Mazepa,0.009009
Ukraine,UAH,hryvna,Bogdan Khmelnitsky,M,1.0,Head of Gov't,No,5,NaN,1992,1657,"1st ""hetman of ukraine"", also military leader",NaN,False,UAH_Bogdon,0.004004
Ukraine,UAH,hryvna,Yaroslav the Wise,M,1.0,Monarch,Yes,2,NaN,1992,1054,1st christian prince of Kiev,First Christian Prince of Kiev,False,UAH_Yaroslav,0.001001
Ukraine,UAH,hryvna,Volodymyr the Great,M,1.0,Monarch,No,1,NaN,1992,1015,NaN,NaN,False,UAH_Great,0.000000

This can be a very powerful operation, but it's easy to get mixed up when
labels are integers, as with the `bill_value` data.

This:

In [61]:
bill_value.loc[0:5]

0    100
1    100
2     50
3     20
4     10
5     50
Name: bill_value, dtype: int64

Is the same as this:

In [62]:
bill_value.iloc[0:5]

0    100
1    100
2     50
3     20
4     10
Name: bill_value, dtype: int64

Recall that bracket notation selects columns in DataFrames. With a Series, the
same notation acts as another way to perform `loc` operations.

In [63]:
bill_value[0:5]

0    100
1    100
2     50
3     20
4     10
Name: bill_value, dtype: int64

Finally, `iloc` and `loc` can be used in tandem with one another. This is
called **chaining**. Below, we use the country-indexed `banknotes` DataFrame to
select all rows with "Peru." Then, we select the second row from this subset.

In [64]:
banknotes.loc["Peru"].iloc[1]

currency_code                                PEN
currency_name                                Sol
name                     Raúl Porras Barrenechea
gender                                         M
bill_count                                   1.0
profession                            Politician
known_for_being_first                         No
current_bill_value                            20
prop_total_bills                             NaN
first_appearance_year                       1991
death_year                                  1960
comments                                     NaN
hover_text                                   NaN
has_portrait                               False
id                                      PEN_Raul
scaled_bill_value                       0.052632
Name: Peru, dtype: object

(indexing-by-condition)=
### Indexing by a Condition

The last way to index in Pandas is by condition. Pandas does this by evaluating
statements and returning a sequence of Boolean values. This is by far the most
powerful method of indexing in Pandas.

Earlier, we used this method to look for bill values that are not divisible by
25.

In [65]:
bill_value % 25 != 0

0      False
1      False
2      False
3       True
4       True
       ...
274     True
275     True
276    False
277    False
278    False
Name: bill_value, Length: 279, dtype: bool

It's possible to perform a similar operation with `loc`:

In [66]:
bill_value.loc[bill_value % 25 != 0]

3      20
4      10
6      10
7      20
8      10
       ..
270    20
272    10
273     5
274    10
275    20
Name: bill_value, Length: 85, dtype: int64

Notice though that not all the data is here. Only those entries where the above
condition is True are returned. This is a **subset** of the Series.

Using square brackets works in the same way with a Series:

In [67]:
bill_value[bill_value - 100 > 5]

15     1000
16      500
17      200
27      200
33      200
       ...
263     200
265    2000
266     500
269     200
278     200
Name: bill_value, Length: 130, dtype: int64

With a DataFrame, you can use square brackets to subset:

In [68]:
banknotes[banknotes["currency_code"] == "MWK"]

,currency_code,currency_name,name,gender,bill_count,profession,known_for_being_first,current_bill_value,prop_total_bills,first_appearance_year,death_year,comments,hover_text,has_portrait,id,scaled_bill_value
country,,,,,,,,,,,,,,,,
Malawi,MWK,Kwacha,Dr. Hastings Kamuzu Banda,M,1.0,Head of Gov't,Yes,1000,NaN,1971,1997,1st President and 1st Prime Minister of Malawi,First President and Prime Minister of Malawi,False,MWK_Hastings,0.494949
Malawi,MWK,Kwacha,Rose Lomathinda Chibambo,F,1.0,Politician,Yes,200,NaN,2012,2016,1st female minister in the independent Malawi ...,First female minister in the independent Malaw...,False,MWK_Rose,0.090909
Malawi,MWK,Kwacha,Inkosi ya Makhosi M'mbelwa II,M,1.0,Monarch,No,20,NaN,2012,1959,cannot find info about this person,NaN,False,MWK_Mmbelwa,0.000000
Malawi,MWK,Kwacha,Inkosi Ya Mokhosi Gomani II,M,1.0,Monarch,No,50,NaN,2012,1954,NaN,NaN,False,MWK_Gomani,0.015152
Malawi,MWK,Kwacha,Reverend John Chilembwe,M,1.0,Revolutionary,No,500,NaN,1997,1915,Known for organizing an uprising against the c...,NaN,False,MWK_Chilembwe,0.242424
Malawi,MWK,Kwacha,Reverend John Chilembwe,M,1.0,Revolutionary,No,2000,NaN,1997,1915,Known for organizing an uprising against the c...,NaN,False,MWK_Chilembwe,1.000000
Malawi,MWK,Kwacha,James Federick Sangala,M,1.0,Politician,No,100,NaN,2012,1974,NaN,NaN,False,MWK_Sangala,0.040404

If you want to specify specific columns, use `loc`:

In [69]:
banknotes.loc[banknotes["current_bill_value"] == 10.0, "currency_name"]

country
Argentina          Argentinian Peso
Australia         Australian Dollar
Australia         Australian Dollar
Bangladesh                     Taka
Bolivia                   Boliviano
Bolivia                   Boliviano
Bolivia                   Boliviano
Canada              Canadian Dollar
Canada              Canadian Dollar
Canada              Canadian Dollar
Canada              Canadian Dollar
Canada              Canadian Dollar
England                       pound
England                       pound
Georgia                        lari
Nigeria                       naira
New Zealand      New Zealand dollar
Peru                            Sol
Peru                            Sol
China                      Renminbi
Serbia                Serbian dinar
Tunisia              Tunisian dinar
Tunisia              Tunisian dinar
Turkey                         Lira
Turkey                         Lira
Ukraine                      hryvna
United States             US dollar
Venezuela        Venezuelan bolivar
South Africa                   rand
Name: currency_name, dtype: object

The above lets you select multiple columns, but you could also do the
following:

In [70]:
cols = ["currency_code", "currency_name"]
banknotes[cols].loc[banknotes["current_bill_value"] == 10.0]

              currency_code       currency_name
country
Argentina               ARS    Argentinian Peso
Australia               AUD   Australian Dollar
Australia               AUD   Australian Dollar
Bangladesh              BDT                Taka
Bolivia                 BOB           Boliviano
Bolivia                 BOB           Boliviano
Bolivia                 BOB           Boliviano
Canada                  CAD     Canadian Dollar
Canada                  CAD     Canadian Dollar
Canada                  CAD     Canadian Dollar
Canada                  CAD     Canadian Dollar
Canada                  CAD     Canadian Dollar
England                 GBP               pound
England                 GBP               pound
Georgia                 GEL                lari
Nigeria                 NGN               naira
New Zealand             NZD  New Zealand dollar
Peru                    PEN                 Sol
Peru                    PEN                 Sol
China                   RMB            Renminbi
Serbia                  RSD       Serbian dinar
Tunisia                 TND      Tunisian dinar
Tunisia                 TND      Tunisian dinar
Turkey                  TRY                Lira
Turkey                  TRY                Lira
Ukraine                 UAH              hryvna
United States           USD           US dollar
Venezuela               VES  Venezuelan bolivar
South Africa            ZAR                rand

(special-values)=
Special Values
--------------

You may have noticed that some of the data in `banknotes` is missing. This is
common, and it's important to understand how to handle missing or invalid
values.

There are many reasons that could cause these values to be missing or incomplete,
and as a result, Pandas provides lots of flexibility for detecting and handling
these values.

In Pandas, these special values, are generally treated as missing values
in the dataset, and are represented by the NumPy `nan` type. This reduces
some of the nuance of data values and types, but was seemingly done
for computational performance reasons.

In [71]:
banknotes.iloc[-25]

currency_code                        USD
currency_name                  US dollar
name                     Abraham Lincoln
gender                                 M
bill_count                           1.0
profession                 Head of Gov't
known_for_being_first                 No
current_bill_value                     5
prop_total_bills                    0.06
first_appearance_year               1914
death_year                          1865
comments                             NaN
hover_text                           NaN
has_portrait                        True
id                           USD_Lincoln
scaled_bill_value               0.040404
Name: United States, dtype: object

(missing-values-in-pandas)=
### Types of Values Considered Missing by Pandas

In addition to `np.nan` (which displays as NaN), Pandas interprets several
other values as missing.  This includes Python's `None` type, as well as
Pandas' experimental `NA` types.

Python's `None` type represents something that has no value. It often comes
about as the return of a function, if something hasn't been defined yet, or if
something wasn't found.

When creating a Series, we can pass this value:

In [72]:
pd.Series([None, "one", "two"])

0    None
1     one
2     two
dtype: object

Be aware that `None` is a Python object, and in the above example, the 
datatype of the series became 'object'. If we specify a datatype explicitly
then Pandas will convert it to one of its representations:

In [73]:
pd.Series([1.5, 2.0, 3, None], dtype="float")

0    1.5
1    2.0
2    3.0
3    NaN
dtype: float64

(missing-values-in-csvs)=
### Reading in Missing Values from a CSV file

An obvious source of missing or incomplete values is the data itself. 
When the data was collected, there may have been reasons to code missing data.
For example, in collection of survey responses, there may be times where the 
answer was not applicable.

Another example would be if a measurement was not taken on some of the samples. 
Obviously, there are no rules on how this was represented in the data set. 
However there are several conventions, and Pandas is aware of many of them. 

When reading data from a CSV file, Pandas will automatically detect missing
values. By default, it will convert any empty cell, or string such as 'na',
'nan', 'null', 'N/A', and other variants to NaN.  A full list can be found in
the [Pandas documentation][readcsv].


[readcsv]: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html


(detecting-missing-values)=
### Detecting Missing Values

To detect missing values, Pandas provides two complementary methods: `isna` and
`notna`.

We can see information about missing values with the `count` method on 
DataFrames:

In [74]:
banknotes.count()

currency_code            279
currency_name            279
name                     279
gender                   279
bill_count               279
profession               279
known_for_being_first    279
current_bill_value       279
prop_total_bills          59
first_appearance_year    279
death_year               272
comments                 119
hover_text                89
has_portrait             279
id                       279
scaled_bill_value        278
dtype: int64

If we look at the `hover_text` columns of the DataFrame, we can see what 
those missing values look like.

In [75]:
ht = banknotes["hover_text"]
ht.count()

89

The return of `isna` is a Boolean Series indicating which of the values are
considered missing:

In [76]:
ht.isna()

country
Argentina        True
Argentina        True
Argentina        True
Argentina        True
Argentina       False
                ...
South Africa    False
South Africa    False
South Africa    False
South Africa    False
South Africa    False
Name: hover_text, Length: 279, dtype: bool

The reverse - to see which values are not considered missing - is returned 
with `notna`:

In [77]:
ht.notna()

country
Argentina       False
Argentina       False
Argentina       False
Argentina       False
Argentina        True
                ...
South Africa     True
South Africa     True
South Africa     True
South Africa     True
South Africa     True
Name: hover_text, Length: 279, dtype: bool

(replacing-missing-values)=
### Replacing Missing Values

We can use this Boolean Series to subset with `loc`. For example, to keep only
the values that aren't missing:

In [78]:
ht.loc[ht.notna()]

country
Argentina                           Designed first Argentine flag
Australia       First Australian Aboriginal writer to be publi...
Australia       First person appointed Dame Commander of the B...
Australia       Founded Royal Flying Doctor Service, the world...
Australia       First Australian woman to serve as a member of...
                                      ...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
Name: hover_text, Length: 89, dtype: object

Pandas also provides a shortcut with the `dropna` method:

In [79]:
ht.dropna()

country
Argentina                           Designed first Argentine flag
Australia       First Australian Aboriginal writer to be publi...
Australia       First person appointed Dame Commander of the B...
Australia       Founded Royal Flying Doctor Service, the world...
Australia       First Australian woman to serve as a member of...
                                      ...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
Name: hover_text, Length: 89, dtype: object

Another strategy may be to fill the missing values. We could do so using the 
`fillna` method:

In [80]:
ht.fillna(-1, inplace=True)
ht

country
Argentina                                                      -1
Argentina                                                      -1
Argentina                                                      -1
Argentina                                                      -1
Argentina                           Designed first Argentine flag
                                      ...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
Name: hover_text, Length: 279, dtype: object

Additionally, the data set may have its own indicator for missing values, e.g
"" or 0. We can convert those to missing using the `replace` method:

In [81]:
ht.replace(-1, np.nan)

country
Argentina                                                     NaN
Argentina                                                     NaN
Argentina                                                     NaN
Argentina                                                     NaN
Argentina                           Designed first Argentine flag
                                      ...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
South Africa    First Black state leader and first President o...
Name: hover_text, Length: 279, dtype: object

Exercises
---------

### Exercise

Python's `range` function offers another way to create a sequence. Read the
help file for this function.

Python's `range` function offers another way to create a sequence of numbers.
Read the help file for this function.

1. Create an example range. How does this differ from a list?
2. Describe the three arguments that you can use in `range`. Give examples of
  each.
3. Convert one of those ranges to a list and print it to screen. What changes
  in the way Python represents this sequence?


### Exercise

Return to the discussion in {numref}`coercion-and-conversion`.

1. Why does `"3" + 4` raise an error?
2. Why does `True - 1` return 0?
3. Why does `int(4.6) < 4.6` return `True`?


### Exercise

Use a search engine or consult StackOverflow to figure out how to subset a
DataFrame with multiple conditions.

1. Create a new DataFrame from `banknotes` with the following conditions:
  current bill value is less than or equal to 20; gender is female; contains
  the columns `country`, `name`, `comments`, `has_portrait`
2. Use a Pandas function to count the number of entries that have portraits.
  How many are there?
3. Return the last available comment. What does it say?