In [1]:
import os

os.chdir("..")

Data Structures
===============

The previous chapter introduced Python, providing enough background to do
simple computations on data sets. This chapter focuses on the foundational
knowledge and skills you'll need to use Python effectively in the long term.
Specifically, it begins with a deep dive into data structures and data types in
Python and Pandas. Then, it explains how to use this knowledge during data
analysis.

:::{admonition} Learning Objectives
* Create lists, arrays, and Pandas Series
* Check the type and class of an object
* Coerce an object into a different type
* Describe and differentiate `NA`, `NaN`, `Inf`, and `NULL`
* Index sequences with empty, integer, string, and logical arguments
* Negate or combine conditions with logic operations
* Subset DataFrames
* Apply functions across DataFrames and Series objects
* Find and remove missing values in a DataFrame and Series
:::


Getting Started
---------------

### Packages

We will be working with two packages in this chapter, NumPy and Pandas. Start
by using what you learned in {numref}`modules` to load these packages with
their conventional aliases.

In [2]:
import numpy as np
import pandas as pd

### Loading Data

In the last chapter, you used Pandas to load tabular data into Python.

In [3]:
banknotes = pd.read_csv("data/banknotes.csv")

Recall that you can select a single column with bracket notation. For the next
little while, you will be working with the `current_bill_value` column. Select
it and assign it to a variable.

In [4]:
bill_value = banknotes["current_bill_value"]

(arrays-lists-sequences)=
Arrays, Lists, and Other Sequences
----------------------------------

(pandas-series)=
### Pandas Series

Now examine the variable you created.

In [5]:
bill_value

0      100
1      100
2       50
3       20
4       10
      ...
274     10
275     20
276     50
277    100
278    200
Name: current_bill_value, Length: 279, dtype: int64

You may notice that the data looks a little different from how it displays in a
DataFrame. This is a visual clue: instead of being its own DataFrame,
`bill_value` is a Pandas **Series**. Series objects in Pandas are
one-dimensional **arrays**, data elements stored in an ordered sequence. They
also contain additional metadata and a lot of extra functionality. As you will
learn in this chapter, both a Series and a DataFrame allow you to:
* summarize data
* handle missing data
* reshape and transform data
* subset and filter data
* merge and combine data

In [6]:
bill_value.name

'current_bill_value'

In [7]:
bill_value.shape

(279,)

(lists)=
### Lists

In actuality, a Series is just one kind of sequence object available to you in
Python. The most common such object is a **list**. A list is a container for
zero or more values. Its values are called **elements**, and its **length** is
the number of elements it contains. Like a Series, a list is ordered, so it has
a first element, second element, and so on up to the length of the list.

You can make a list by enclosing comma-separated values in square brackets
`[]`, like this:

In [8]:
[1, 2, 3]

[1, 2, 3]

Lists can be empty:

In [9]:
[]

[]

You can also convert certain objects to lists with `list`:

In [10]:
list(bill_value)

[100,
 100,
 50,
 20,
 10,
 50,
 10,
 20,
 10,
 50,
 100,
 100,
 20,
 5,
 20,
 1000,
 500,
 200,
 100,
 50,
 10,
 5,
 2,
 50,
 50,
 10,
 100,
 200,
 100,
 50,
 10,
 10,
 20,
 200,
 20,
 200,
 100,
 20,
 5,
 50,
 100,
 10,
 10,
 10,
 10,
 10,
 20,
 5000,
 1000,
 10000,
 20000,
 2000,
 50000,
 20000,
 2000,
 10000,
 100000,
 1000,
 20000,
 5000,
 50000,
 2000,
 10000,
 10000,
 5000,
 20000,
 50000,
 2000,
 1000,
 2000,
 5000,
 1000,
 200,
 500,
 5000,
 2000,
 1000,
 500,
 200,
 100,
 200,
 200,
 200,
 500,
 2000,
 100,
 2000,
 100,
 100,
 20,
 500,
 5,
 50,
 20,
 10,
 5,
 10,
 20,
 50,
 5,
 2,
 200,
 1,
 10,
 20,
 50,
 100,
 500,
 100000,
 5000,
 100000,
 10000,
 50000,
 20000,
 50000,
 20000,
 2000,
 1000,
 2000,
 10000,
 200,
 100,
 50,
 20,
 2000,
 500,
 10000,
 5000,
 1000,
 500,
 1000,
 100,
 50,
 500,
 1000,
 10000,
 5000,
 5000,
 500,
 200,
 20,
 100,
 50,
 1000,
 5000,
 1000,
 50000,
 10000,
 1000,
 200,
 20,
 50,
 500,
 2000,
 100,
 500,
 500,
 1000,
 1000,
 1000,
 500,
 20,
 200,
 200,
 100,
 100,
 20,
 500,
 1000,
 10,
 100,
 5,
 20,
 200,
 1000,
 5,
 50,
 100,
 10,
 20,
 100,
 20,
 10,
 10,
 50,
 100,
 200,
 50,
 500,
 100,
 500,
 200,
 20,
 50,
 1000,
 1000,
 1000,
 1,
 5,
 10,
 20,
 50,
 100,
 5000,
 2000,
 100,
 1000,
 500,
 200,
 50,
 10,
 20,
 200,
 500,
 20,
 100,
 50,
 1000,
 100000,
 200,
 500,
 1000,
 5000,
 10000,
 20000,
 50000,
 10,
 20,
 10,
 5,
 5,
 10,
 20,
 50,
 100,
 200,
 10,
 5,
 50,
 20,
 100,
 200,
 50,
 1000,
 20,
 200,
 100,
 500,
 10,
 5,
 2,
 1,
 50,
 2,
 5,
 1,
 20,
 100,
 10,
 1000,
 100,
 20,
 500,
 200,
 50,
 2000,
 500,
 50,
 2,
 200,
 20,
 100,
 10,
 5,
 10,
 20,
 50,
 100,
 200]

Unlike a Series, which is built on top of NumPy arrays, the elements of a list
can be qualitatively different. For instance, this list contains a number,
string, and another list (with one element):

In [11]:
l = [8, "hello", [4.2]]
l

[8, 'hello', [4.2]]

You can get the length of a list with the built-in `len` function:

In [12]:
len(l)

3

(indexing)=
### Indexing

Square brackets `[]` also serve as the **indexing operator** in Python. The
indexing operator gets or sets an element of a list based on the element's
position. Python uses **zero-based indexing**, which means the first element of
a data structure is at position 0. The code to get the first element of the
list `l` is:

In [13]:
l[0]

8

Likewise, getting the third element is:

In [14]:
l[2]

[4.2]

The above logic extends to sequences stored inside sequences. Below, we get the
value  stored in the sublist of `l`.

In [15]:
l[2][0]

4.2

You can set the element of a list by assigning a value at that index. So the
code to change the first element of `l` to the string "hi" is:

In [16]:
l[0] = "hi"
l

['hi', 'hello', [4.2]]

(references)=
### References

Assigning values to a list by its index positions is not without complication.
Suppose you assign a list to a variable `x` and then create a new variable,
`y`, from `x`. If you change an element of `y`, it will also change `x`:

In [17]:
x = [1, 2]
y = x
y[0] = 10
x

[10, 2]

This happens because of the way Python handles variables. In Python, variables
point, or **refer**, to a location in your computer's memory. New variables
created from the same data continue to point to that data unless directed
otherwise, and thus operations on separate variables, or **references** can
affect the same data.

The same holds true for Pandas objects. The variable `bill_value` is only a
reference to a portion of the data `banknotes` represents.

We take a **copy** of objects to create a new reference when assigning
variables:

In [18]:
x = [1, 2]
y = x.copy()
y[0] = 10
x

[1, 2]

You can also convert your list to a **tuple** to prevent problems with value
assignments. Tuples operate similarly to lists, but they are **immutable**.
That is, once you create one, you cannot alter it.

In [19]:
x = [1, 2]
y = x
x = tuple(x)
y[0] = 10
x

(1, 2)

To check what kind of object, or **class**, a variable represents, use the
built-in `type` function.

In [20]:
type(y)

list

In [21]:
type(x)

tuple

In [22]:
type(bill_value)

pandas.core.series.Series

(data-types)=
Data Types
----------

Recall that a list can contain qualitatively different objects, whereas a
Series cannot. What happens, then, if you were to convert `l` into a Series?

In [23]:
pd.Series(l)

0       hi
1    hello
2    [4.2]
dtype: object

Notice that the `dtype` value, which applies to all values in the Series, is
`object`. This is a Pandas catchall for columns with mixed data types and for
ones with strings. Why did converting `l` to a Series change the data type?

To answer this, you need to know about how Python handles different types of
data, including numeric and non-numeric data. You already caught a glimpse of
these data types in {numref}`summarizing-data`, when you used `info` to inspect
a DataFrame. Types are listed in the `Dtype` column.

In [24]:
banknotes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   currency_code          279 non-null    object
 1   country                279 non-null    object
 2   currency_name          279 non-null    object
 3   name                   279 non-null    object
 4   gender                 279 non-null    object
 5   bill_count             279 non-null    float64
 6   profession             279 non-null    object
 7   known_for_being_first  279 non-null    object
 8   current_bill_value     279 non-null    int64
 9   prop_total_bills       59 non-null     float64
 10  first_appearance_year  279 non-null    int64
 11  death_year             272 non-null    object
 12  comments               119 non-null    object
 13  hover_text             89 non-null     object
 14  has_portrait           279 non-null    bool
 15  id                     279 non-null    object
 16  scaled_bill_value      278 non-null    float64
dtypes: bool(1), float64(3), int64(2), object(11)
memory usage: 35.3+ KB

Some of these types are built into Python, while others are specific to Pandas.
Pandas does more work than Python to ensure consistency and specificity across
data types. This is because Pandas is built around NumPy, which provides more
control to the programmer by adding extra data types to best match programming
tasks. This also comes with improved memory and time performance.

A list of data types that you will often encounter in data analysis is below.
Entries marked with \* are NumPy/Pandas extensions to base Python types.
* Boolean
* Integer
* Float
* String
* Complex
* Datetime\*
* Time Delta\*
* StringDtype\*
* Object\*


(numeric-types)=
### Numeric Types

From `banknotes.info()` we learn that `current_bill_value` has an `int64` type.
Integers are one of the two ways that Python stores numeric data. When storing
whole numbers, such as 0, 3, 3000, etc., Python uses integers

The `64` part is an add-on from Pandas. Here, `64` refers to the number of bits
used to store the data, which in turn affects the range of numbers a variable
can hold. Normally though, Python just records the `int`, as in the case below,
where we use `type` to identify a data type:

In [25]:
type(4)

int

Typically, `int` numbers are 32 bits.

Why is bit size important? Consider the fact that a 64-bit integer can hold
values between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807,
whereas a 16-bit integer covers everything between -32,768 and 32,767. Knowing
this information really matters when you're working with large numbers. Without
that knowledge, you might assign 32,768 to an `int16` variable and find that
you've caused an **overflow** error.

The same holds for instances where you need a certain amount of precision in
your data. For example, Python and NumPy have the ability to represent
irrational numbers, like pi. Ultimately, your computer has to represent such
numbers with decimal values, so the number of decimal places a variable can
hold will affect what pi "means" in your code:

In [26]:
np.pi

3.141592653589793

The above is an example of a `float` (for floating point number) type. Use this
when you need decimal precision of any kind:

In [27]:
banknotes["bill_count"]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
274    1.0
275    1.0
276    1.0
277    1.0
278    1.0
Name: bill_count, Length: 279, dtype: float64

You can explicitly construct both numeric data types in Python. Here is an
integer:

In [28]:
n = int(4)

Importantly, this doesn't allow for decimal points:

In [29]:
n = int(4.67)
n

4

The `float` constructor will, however:

In [30]:
n = float(4.67)
n

4.67

Though `int` won't accept a decimal, you can perform arithmetic operations
across numeric types. For example, multiply `current_bill_value` by one and a
half times its current value:

In [31]:
bill_value * 1.5

0      150.0
1      150.0
2       75.0
3       30.0
4       15.0
       ...
274     15.0
275     30.0
276     75.0
277    150.0
278    300.0
Name: current_bill_value, Length: 279, dtype: float64

Notice that the `dtype` has changed from `int64` to `float64`. Python does this
automatically, converting the more limited data type to match the more complex
one. In this case, that means converting integers, which can't hold decimals,
to floats, which can.


(booleans)=
### Booleans

The most limited data type is `bool`, or a Boolean. It is a logical value that
stores either True or False. Booleans are commonly used for expressions with
yes-or-no responses, or for storing the state of your code.

In [32]:
banknotes["has_portrait"]

0      True
1      True
2      True
3      True
4      True
       ...
274    True
275    True
276    True
277    True
278    True
Name: has_portrait, Length: 279, dtype: bool

In [33]:
coded_in_java = False
type(coded_in_java)

bool

(strings)=
### Strings

String objects, or `str`, are the most complex data type. They have the most
attributes and methods associated with them, and they also take up the most
amount of memory.

Use double `"` or single `'` quotes to construct a string:

In [34]:
"Hello, world!"

'Hello, world!'

Back in Pandas, strings are stored under the `object` data type.

In [35]:
banknotes["name"]

0                       Eva Perón
1            Julio Argentino Roca
2      Domingo Faustino Sarmiento
3            Juan Manuel de Rosas
4                 Manuel Belgrano
                  ...
274                Nelson Mandela
275                Nelson Mandela
276                Nelson Mandela
277                Nelson Mandela
278                Nelson Mandela
Name: name, Length: 279, dtype: object

This is because strings aren't fixed-length sequences, like numbers are. So
Pandas has to provide extra room for the possibility that a string will become
shorter or longer.


(coercion-and-conversion)=
### Coercion and Conversion

Since arrays like a Series have to contain the same data type throughout,
Pandas will automatically convert all elements in a Series to an `object` when
even just one element is a string. This is known as implicit **type coercion**.
It's why all the components of the list `l` became `objects`.

You've actually seen a few examples of this already. Multiplying the `int64`
Series `bill_value` by the `float` 1.5 produced `float` numbers. The same holds
for:

In [36]:
8 / 0.25

32.0

And:

In [37]:
True + 2

3

In the above, Python converts `True` to `1` and then performs the arithmetic.

**Type conversion** is when you change an object's data type in an explicit
manner.

In [38]:
b = int(4.5)
b

4

...is the example you saw earlier. Here is another:

In [39]:
bool(0)

False

And one more:

In [40]:
str(105)

'105'

Python can even read strings like numbers and Boolean values:

In [41]:
float("7.3")

7.3

In [42]:
bool("True")

True

Note however that such operations have to be logically sound. This will not
work:

In [43]:
int("Hello world!")

ValueError: invalid literal for int() with base 10: 'Hello world!'

(comparison-operators)=
### Comparison Operators

Programming tasks often involve comparing variables. Use **comparison
operators** to do so.

| Symbol | Meaning                  |
| :----: | :----------------------- |
| `<`    | less than                |
| `>`    | greater than             |
| `<=`   | less than or equal to    |
| `>=`   | greater than or equal to |
| `==`   | equal to                 |
| `!=`   | not equal to             |

Notice that the "equal to" operator is two equal signs. This is to distinguish
it from the assignment `=` operator.

In [44]:
sum(bill_value) < 10000

False

In [45]:
bill_value == banknotes["current_bill_value"]

0      True
1      True
2      True
3      True
4      True
       ...
274    True
275    True
276    True
277    True
278    True
Name: current_bill_value, Length: 279, dtype: bool

In [46]:
bill_value % 25 != 0

0      False
1      False
2      False
3       True
4       True
       ...
274     True
275     True
276    False
277    False
278    False
Name: current_bill_value, Length: 279, dtype: bool

In [47]:
parks = pd.read_csv("data/parks_final.csv")

## Series

Each column in the DataFrame is a Pandas `Series` object.
A Series is a collection of values that all share the same data type. 
In addition, each value has a label, these labels don't need to be unique
and by default are integers starting at 0.

It is built on top of the NumPy ndarray object, and as such, will
perform much faster than the list object for numerical operations.

Lets look at the year column of our data. We can access it with the following:

In [48]:
year = parks["year"].copy()

In this case, we have assigned a copy of the year column from the parks 
dataframe to a variable we call year. If we didn't use the copy method,
then modifications we made to year, would also modify that column
in the DataFrame. This way, we can make changes without effecting
the original.

As with DataFrames, there are several functions for exploring series.

To get the first values, we can once again use `head`:

In [49]:
year.head()

0    2020
1    2020
2    2020
3    2020
4    2020
Name: year, dtype: int64

And again, to get the last values we can use `tail`:

In [50]:
year.tail()

741    2012
742    2012
743    2012
744    2012
745    2012
Name: year, dtype: int64

Since the data is numeric we can also get some summary data:

In [51]:
year.describe()

count     746.000000
mean     2016.652815
std         2.371271
min      2012.000000
25%      2015.000000
50%      2017.000000
75%      2019.000000
max      2020.000000
Name: year, dtype: float64

To see just the unique set of values we can use the `unique` method:

In [52]:
year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012])

Another very useful summary is `value_counts`:

In [53]:
year.value_counts()

2017    104
2016    103
2018    102
2020    101
2019    101
2015     78
2014     63
2013     52
2012     42
Name: year, dtype: int64

Series are powerful because we can apply operations on them in an element wise
fashion very easily and efficiently. For example:

In [54]:
year + 10

0      2030
1      2030
2      2030
3      2030
4      2030
       ...
741    2022
742    2022
743    2022
744    2022
745    2022
Name: year, Length: 746, dtype: int64

In addition, we can also use comparison operators:

In [55]:
year > 2014

0       True
1       True
2       True
3       True
4       True
       ...
741    False
742    False
743    False
744    False
745    False
Name: year, Length: 746, dtype: bool

### Indexing Series

There are three main methods for accessing specific values in Pandas:
1. by integer position
2. by label/name
3. based on a boolean array

These methods apply to Series, and as we will see later, to DataFrames.

### Selecting Values By Integer Position

To access elements in a Series by integer position, use the `iloc` attribute:

In [56]:
year.iloc[33]

2020

We can also pass a list or array of integer locations:

In [57]:
year.iloc[[33,0,23]]

33    2020
0     2020
23    2020
Name: year, dtype: int64

As with lists, we can use Python's slice operator:

In [58]:
year.iloc[3:10]

3    2020
4    2020
5    2020
6    2020
7    2020
8    2020
9    2020
Name: year, dtype: int64

### Selecting Values By Label

A Series in Pandas has labels attached to each value, in what Pandas calls
the index. 
We can see the index of a Series with the `index` attribute:

In [59]:
year.index

RangeIndex(start=0, stop=746, step=1)

Here we see that the index the index is a collection of integers. 
We can change that to something a little more descriptive.

In [60]:
year.index = parks["city"]
year.index

Index(['Minneapolis', 'Washington', 'St. Paul', 'Arlington', 'Cincinnati',
       'Portland', 'Irvine', 'San Francisco', 'Boston', 'Chicago',
       ...
       'Tucson', 'Memphis', 'Oklahoma City', 'Jacksonville', 'San Antonio',
       'Indianapolis', 'Mesa', 'Louisville', 'Charlotte', 'Fresno'],
      dtype='object', name='city', length=746)

To access elements based on label or name, we use the `loc` attribute:

In [61]:
year.loc["St. Paul"]

city
St. Paul    2020
St. Paul    2019
St. Paul    2018
St. Paul    2017
St. Paul    2016
St. Paul    2015
Name: year, dtype: int64

Notice that there were multiple values that matched with that label, so the
Series returned all of them.

We can also pass a list or array of labels:

In [62]:
year.loc[["St. Paul", "Mesa", "Fresno"]]

city
St. Paul    2020
St. Paul    2019
St. Paul    2018
St. Paul    2017
St. Paul    2016
St. Paul    2015
Mesa        2020
Mesa        2019
Mesa        2018
Mesa        2017
Mesa        2016
Mesa        2015
Mesa        2014
Mesa        2013
Mesa        2012
Fresno      2020
Fresno      2019
Fresno      2018
Fresno      2017
Fresno      2016
Fresno      2015
Fresno      2014
Fresno      2013
Fresno      2012
Name: year, dtype: int64

Additionally, Pandas supports the more conventional `[]` operator, directly
on Series.
We can pass labels to this operator:

In [63]:
year[["Irvine", "San Diego"]]

city
Irvine       2020
Irvine       2019
Irvine       2018
Irvine       2017
Irvine       2016
San Diego    2020
San Diego    2019
San Diego    2018
San Diego    2017
San Diego    2016
San Diego    2015
San Diego    2014
San Diego    2013
San Diego    2012
Name: year, dtype: int64

### Selecting Values Based On A Boolean Array

The third way to select values is based on a Boolean array. 
The Boolean array must have the same length as the number of elements
in the Series.

This is a really powerful method, that ties in well with functions that 
create Boolean Series.

For example, with the example from earlier:

In [64]:
year.loc[year > 2014]

city
Minneapolis      2020
Washington       2020
St. Paul         2020
Arlington        2020
Cincinnati       2020
                 ...
Oklahoma City    2015
Louisville       2015
Indianapolis     2015
Charlotte        2015
Fresno           2015
Name: year, Length: 589, dtype: int64

The `[]` operator also accepts Boolean Series:

In [65]:
year[year > 2014]

city
Minneapolis      2020
Washington       2020
St. Paul         2020
Arlington        2020
Cincinnati       2020
                 ...
Oklahoma City    2015
Louisville       2015
Indianapolis     2015
Charlotte        2015
Fresno           2015
Name: year, Length: 589, dtype: int64

(indexing-dataframes)=
## Indexing DataFrames

Conceptually, indexing DataFrames is very similar to the operations on Series. 
However, whereas Series are one dimensional, DataFrames are two dimensional.
A DataFrame is a collection of Series, organized as columns.

As with Series, we can use `iloc` to select rows based on their integer 
position:

In [66]:
parks.iloc[[300, 200, -1]]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
300,2018,94,Fresno,2.2,4.0,4%,3.0,62%,19.0,$42,...,1.0,15.0,19.0,50.0,30.9,NaN,California,542107.0,494665.0,115.2
200,2019,95,Charlotte/Mecklenburg County,16.5,50.0,6%,12.5,36%,7.5,$48,...,0.7,25.0,27.9,NaN,28.9,NaN,North Carolina,NaN,NaN,NaN
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

And we can use `loc` to select based on label, in this case the label is 
also integers:

In [67]:
parks.loc[732]

year                             2012
rank                               27
city                         Columbus
med_park_size_data                6.6
med_park_size_points             13.0
park_pct_city_data               8.1%
park_pct_city_points              8.0
pct_near_park_data                49%
pct_near_park_points             16.0
spend_per_resident_data        $68.94
spend_per_resident_points         6.0
basketball_data                   NaN
basketball_points                 NaN
dogpark_data                      NaN
dogpark_points                    NaN
playground_data                   1.9
playground_points                 7.0
rec_sr_data                       NaN
rec_sr_points                     NaN
restroom_data                     NaN
restroom_points                   NaN
splashground_data                 NaN
splashground_points               NaN
amenities_points                  NaN
total_points                     50.0
total_pct                        41.5
park_benches                      2.0
state                            Ohio
pop2020                      905748.0
pop2010                      787033.0
area2020                        220.0
Name: 732, dtype: object

Again, as with Series, we can use boolean arrays or lists to index:

In [68]:
parks.loc[parks["state"] == "California"]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
6,2020,7,Irvine,6.1,28.0,27%,50.0,82%,73.0,$215,...,0.7,25.0,67.3,318.0,79.6,NaN,California,307670.0,212375.0,65.6
7,2020,8,San Francisco,1.3,4.0,21%,50.0,100%,100.0,$399,...,1.0,36.0,61.7,316.0,78.9,NaN,California,873965.0,805235.0,46.9
17,2020,18,San Diego,6.8,32.0,19%,50.0,81%,71.0,$153,...,0.1,2.0,37.2,276.0,69.0,NaN,California,1386932.0,1307402.0,325.9
22,2020,23,Long Beach,3.2,14.0,10%,25.0,84%,76.0,$180,...,0.2,4.0,50.0,265.0,66.3,NaN,California,466742.0,462257.0,50.7
30,2020,30,Sacramento,5.4,25.0,9%,21.0,83%,75.0,$122,...,4.5,100.0,60.2,248.0,62.0,NaN,California,524943.0,466488.0,98.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2012,8,San Diego,6.7,14.0,22.8%,20.0,75%,28.0,$121.47,...,NaN,NaN,NaN,81.0,67.5,4.0,California,1386932.0,1307402.0,325.9
715,2012,12,San Jose,3.7,8.0,14.1%,15.0,69%,26.0,$135.68,...,NaN,NaN,NaN,76.0,63.5,3.5,California,1013240.0,945942.0,178.3
723,2012,19,Long Beach,3.2,7.0,10.3%,11.0,70%,26.0,$130.54,...,NaN,NaN,NaN,62.0,51.5,2.5,California,466742.0,462257.0,50.7
729,2012,25,Los Angeles,6.7,14.0,14.1%,15.0,52%,18.0,$55.14,...,NaN,NaN,NaN,52.0,43.5,2.0,California,3898747.0,3792621.0,469.5
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

This also works with just the `[]` operator:

In [69]:
parks[parks["state"] == "California"]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
6,2020,7,Irvine,6.1,28.0,27%,50.0,82%,73.0,$215,...,0.7,25.0,67.3,318.0,79.6,NaN,California,307670.0,212375.0,65.6
7,2020,8,San Francisco,1.3,4.0,21%,50.0,100%,100.0,$399,...,1.0,36.0,61.7,316.0,78.9,NaN,California,873965.0,805235.0,46.9
17,2020,18,San Diego,6.8,32.0,19%,50.0,81%,71.0,$153,...,0.1,2.0,37.2,276.0,69.0,NaN,California,1386932.0,1307402.0,325.9
22,2020,23,Long Beach,3.2,14.0,10%,25.0,84%,76.0,$180,...,0.2,4.0,50.0,265.0,66.3,NaN,California,466742.0,462257.0,50.7
30,2020,30,Sacramento,5.4,25.0,9%,21.0,83%,75.0,$122,...,4.5,100.0,60.2,248.0,62.0,NaN,California,524943.0,466488.0,98.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2012,8,San Diego,6.7,14.0,22.8%,20.0,75%,28.0,$121.47,...,NaN,NaN,NaN,81.0,67.5,4.0,California,1386932.0,1307402.0,325.9
715,2012,12,San Jose,3.7,8.0,14.1%,15.0,69%,26.0,$135.68,...,NaN,NaN,NaN,76.0,63.5,3.5,California,1013240.0,945942.0,178.3
723,2012,19,Long Beach,3.2,7.0,10.3%,11.0,70%,26.0,$130.54,...,NaN,NaN,NaN,62.0,51.5,2.5,California,466742.0,462257.0,50.7
729,2012,25,Los Angeles,6.7,14.0,14.1%,15.0,52%,18.0,$55.14,...,NaN,NaN,NaN,52.0,43.5,2.0,California,3898747.0,3792621.0,469.5
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

To access columns from a DataFrame, we use the `[]` operator, as we have 
already seen:

In [70]:
parks["pop2020"]

0      429954.0
1      689545.0
2      311527.0
3           NaN
4      309317.0
         ...
741    887642.0
742    504258.0
743    633045.0
744    874579.0
745    542107.0
Name: pop2020, Length: 746, dtype: float64

We can also pass a list of column names, in any order:

In [71]:
parks[["pop2020", "city"]]

      pop2020          city
0    429954.0   Minneapolis
1    689545.0    Washington
2    311527.0      St. Paul
3         NaN     Arlington
4    309317.0    Cincinnati
..        ...           ...
741  887642.0  Indianapolis
742  504258.0          Mesa
743  633045.0    Louisville
744  874579.0     Charlotte
745  542107.0        Fresno

[746 rows x 2 columns]

If we select a single column from the DataFrame, we get a Series, 
which we can index as we saw before:

In [72]:
parks["pop2020"].iloc[1:10]

1     689545.0
2     311527.0
3          NaN
4     309317.0
5     652503.0
6     307670.0
7     873965.0
8     675647.0
9    2746388.0
Name: pop2020, dtype: float64

So, to combine with what we saw before with boolean indexing:

In [73]:
parks[["city", "pop2020"]].loc[parks["state"] == "California"]

              city    pop2020
6           Irvine   307670.0
7    San Francisco   873965.0
17       San Diego  1386932.0
22      Long Beach   466742.0
30      Sacramento   524943.0
..             ...        ...
711      San Diego  1386932.0
715       San Jose  1013240.0
723     Long Beach   466742.0
729    Los Angeles  3898747.0
745         Fresno   542107.0

[129 rows x 2 columns]

A more elegant approach to the above is to use:

In [74]:
parks.loc[parks["state"] == "California", ["city", "pop2020"]]

              city    pop2020
6           Irvine   307670.0
7    San Francisco   873965.0
17       San Diego  1386932.0
22      Long Beach   466742.0
30      Sacramento   524943.0
..             ...        ...
711      San Diego  1386932.0
715       San Jose  1013240.0
723     Long Beach   466742.0
729    Los Angeles  3898747.0
745         Fresno   542107.0

[129 rows x 2 columns]

## Special Values

Often times, the data we have will work with has missing, or invalid data.
Its important to understand these values, and how to work with them in Pandas.

There are many reasons that could cause these values to be missing or incomplete,
and as a result, Pandas provides lots of flexibility for detecting and handling
these values.

In Pandas, these special values, are generally treated as missing values
in the dataset, and are represented by the NumPy `nan` type. This reduces
some of the nuance of data values and types, but was seemingly done
for computational preformance reasons.

### Types of Values Considered Missing by Pandas

In addition to `np.nan` (which displays as NaN), Pandas interprets 
several other values as missing. 
This includes Python's `None` type, as well as Pandas' experimental `NA` types.

Python's `None` type represents something that has no value. 
It often comes about as the return of a function, if something hasn't
been defined yet, or if something wasn't found.

When creating a Series, we can pass this value:

In [75]:
pd.Series([None, "one", "two"])

0    None
1     one
2     two
dtype: object

Be aware that `None` is a Python object, and in the above example, the 
datatype of the series became 'object'. If we specify a datatype explicitly
then Pandas will convert it to one of its representations:

In [76]:
pd.Series([1.5,2.0,3, None], dtype="float")

0    1.5
1    2.0
2    3.0
3    NaN
dtype: float64

Be aware that `None` is a Python object, and in the above example, the 
datatype of the series became 'object'. If we specify a datatype explicitly
then Pandas will convert it to one of its representations:

In [77]:
pd.Series(["the", "and", None], dtype="string")

0     the
1     and
2    <NA>
dtype: string

### Reading in Missing Values from a CSV file

An obvious source of missing or incomplete values is the data itself. 
When the data was collected, there may have been reasons to code missing data.
For example, in collection of survey responses, there may be times where the 
answer was not applicable. 
Another example would be if a measurement was not taken on some of the samples. 
Obviously, there are no rules on how this was represented in the data set. 
However there are several conventions, and Pandas is aware of many of them. 

When reading data from a CSV file, Pandas will automatically detect missing 
values. 
By default, it will convert any empty cell, or string such as 'na', 'nan', 'null',
'N/A', and other variants to NaN.
A full list can be found in the Pandas documentation: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html


### Detecting Missing Values

To detect missing values, Pandas provides two complementary methods - 
`isna` and `notna`.

We can see information about missing values with the `count` method on 
DataFrames:

In [78]:
parks.count()

year                         746
rank                         746
city                         746
med_park_size_data           746
med_park_size_points         746
park_pct_city_data           746
park_pct_city_points         746
pct_near_park_data           746
pct_near_park_points         746
spend_per_resident_data      746
spend_per_resident_points    746
basketball_data              589
basketball_points            589
dogpark_data                 589
dogpark_points               589
playground_data              746
playground_points            746
rec_sr_data                  589
rec_sr_points                589
restroom_data                304
restroom_points              304
splashground_data            304
splashground_points          304
amenities_points             589
total_points                 582
total_pct                    642
park_benches                 442
state                        746
pop2020                      739
pop2010                      739
area2020                     739
dtype: int64

If we look at the `park_benches` columns of the DataFrame, we can see what 
those missing values look like.

In [79]:
pb = parks["park_benches"]
pb.count()

442

The return of `isna` is a boolean Series indicating which of the values 
are considered missing:

In [80]:
pb.isna()

0       True
1       True
2       True
3       True
4       True
       ...
741    False
742    False
743    False
744    False
745    False
Name: park_benches, Length: 746, dtype: bool

The reverse - to see which values are not considered missing - is returned 
with `notna`:

In [81]:
pb.notna()

0      False
1      False
2      False
3      False
4      False
       ...
741     True
742     True
743     True
744     True
745     True
Name: park_benches, Length: 746, dtype: bool

### Replacing Missing Values

We can use this boolean Series to subset. 
For example, to keep only the values that aren't missing:

In [82]:
pb.loc[pb.notna()]

304    5.0
305    5.0
306    5.0
307    4.5
308    4.5
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 442, dtype: float64

Pandas also provides a shortcut with the `dropna` method:

In [83]:
pb.dropna()

304    5.0
305    5.0
306    5.0
307    4.5
308    4.5
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 442, dtype: float64

Another strategy may be to fill the missing values. We could do so using the 
`fillna` method:

In [84]:
pb.fillna(-1)

0     -1.0
1     -1.0
2     -1.0
3     -1.0
4     -1.0
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 746, dtype: float64

Additionally, the data set may have its own indicator for missing values, 
e.g "" or 0. We can convert those to missing using the `replace` method:

In [85]:
pb.replace(-1, np.nan)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 746, dtype: float64