Pandas Data Structures
======================


:::{admonition} Learning Objectives
- Load a DataFrame from a CSV file
- Inspect the structure of DataFrame
- Learn Python and Pandas data types
- Index Series using integer position, labels, and Booleans
- Index DataFrames using integer position, labels, and Booleans
- Find and remove missing values in a Series and DataFrame
:::


## Recap 

Reader Link: https://ucdavisdatalab.github.io/workshop_python_basics/chapters/02_pandas-basics.html  

Data Link: https://raw.githubusercontent.com/ucdavisdatalab/workshop_python_basics/main/data/parks_final.csv  

### Packages

When packages are installed, they can be loaded into the Python session with
the `import` command. To avoid having to type the full name of the module
we define an alias using the `as` keyword. By convention, the alias for
`numpy` is `np` and the alias for `pandas` is `pd`. 

Let's start by loading in NumPy and Pandas:

In [1]:
import numpy as np
import pandas as pd

### Pandas

**Pandas** is a package that provides objects and many functions for working 
with data. It is very popular and used for tasks such as:
- loading and writing data to/from files and databases
- summarizing data
- handling missing data
- reshaping and transforming data
- subsetting and filtering data
- merging and combining datasets


### Load in data

First, we will load in the dataset from a CSV file using the `read_csv`
function from Pandas: 

:::{Tip} 
Most functions in Pandas will have documentation describing what the function 
does and how to use it. You can find this documentation online or directly
from the Python shell using the built-in help system: `help(pd.read_csv)`.
In IPython environments, you can use `?` either before or after the function
name as a shorthand for the help function: `?pd.read_csv`

This will also work on many objects and classes. 
:::

In [2]:
parks = pd.read_csv("../data/parks_final.csv")

We can use the `head` method to see what we have.

In [3]:
parks.head()

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
0,2020,1,Minneapolis,5.7,26.0,15%,38.0,98%,98.0,$319,...,4.0,100.0,79.3,341.0,85.3,NaN,Minnesota,429954.0,382578.0,54.0
1,2020,2,Washington,1.4,5.0,24%,50.0,98%,98.0,$307,...,4.1,100.0,80.3,333.0,83.3,NaN,District of Columbia,689545.0,601723.0,61.1
2,2020,3,St. Paul,3.2,14.0,15%,39.0,99%,99.0,$219,...,1.3,47.0,78.0,330.0,82.5,NaN,Minnesota,311527.0,285068.0,52.0
3,2020,4,Arlington,2.4,10.0,11%,28.0,99%,99.0,$301,...,2.2,81.0,89.0,326.0,81.5,NaN,Virginia,NaN,NaN,NaN
4,2020,5,Cincinnati,4.4,20.0,14%,36.0,82%,74.0,$190,...,4.5,100.0,92.5,323.0,80.6,NaN,Ohio,309317.0,296943.0,77.8

Here we see a DataFrame, which is the really important part of Pandas, which we
will spend lots of time with during this lesson and the next. 
The dataframe is the tool we can merge, join, summarize, etc.

## DataFrames

A **DataFrame** is how Pandas structures tabular data - data structured as rows
and columns. In general rows are observations, and columns are variables.
Each entry is called a cell.


### Methods for Exploring DataFrames

As with the `head` method there are many other methods for looking 
at the contents of a Pandas DataFrame.

`head` shows the first rows of the DataFrame, to see the last rows, use
`tail`. By default, the number of rows displayed is 5, this amount
can be modified by passing an optional integer argument to the function call.
Both `head` and `tail` accept this optional integer argument.

In [4]:
parks.tail(10)

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
736,2012,31,Tucson,4.1,8.0,2.7%,1.0,52%,18.0,$100.64,...,NaN,NaN,NaN,46.0,38.5,2.0,Arizona,542629.0,520116.0,241.0
737,2012,31,Memphis,10.0,20.0,4.5%,4.0,40%,12.0,$60.32,...,NaN,NaN,NaN,46.0,38.5,2.0,Tennessee,633104.0,646889.0,297.0
738,2012,33,Oklahoma City,6.7,14.0,5.6%,5.0,43%,12.0,$61.02,...,NaN,NaN,NaN,44.0,36.5,1.5,Oklahoma,681054.0,579999.0,606.2
739,2012,34,Jacksonville,5.0,10.0,9.2%,9.0,30%,4.0,$44.82,...,NaN,NaN,NaN,43.0,36.0,1.5,Florida,949611.0,821784.0,747.3
740,2012,35,San Antonio,11.1,20.0,7.9%,8.0,32%,6.0,$62.79,...,NaN,NaN,NaN,42.0,35.0,1.5,Texas,1434625.0,1327407.0,498.8
741,2012,36,Indianapolis,10.3,20.0,4.8%,4.0,32%,6.0,$43.61,...,NaN,NaN,NaN,37.0,31.0,1.5,Indiana,887642.0,820445.0,361.6
742,2012,36,Mesa,3.2,7.0,2.6%,1.0,60%,22.0,$60.96,...,NaN,NaN,NaN,37.0,31.0,1.5,Arizona,504258.0,439041.0,138.7
743,2012,38,Louisville,7.3,15.0,6.7%,6.0,32%,6.0,$50.76,...,NaN,NaN,NaN,35.0,29.0,1.0,Kentucky,633045.0,597337.0,263.5
744,2012,39,Charlotte,19.9,20.0,4.1%,3.0,26%,2.0,$78.94,...,NaN,NaN,NaN,34.0,28.5,1.0,North Carolina,874579.0,731424.0,308.3
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

To display the columns of the DataFrame we can access the columns attribute
of the DataFrame object.

In [5]:
parks.columns

Index(['year', 'rank', 'city', 'med_park_size_data', 'med_park_size_points',
       'park_pct_city_data', 'park_pct_city_points', 'pct_near_park_data',
       'pct_near_park_points', 'spend_per_resident_data',
       'spend_per_resident_points', 'basketball_data', 'basketball_points',
       'dogpark_data', 'dogpark_points', 'playground_data',
       'playground_points', 'rec_sr_data', 'rec_sr_points', 'restroom_data',
       'restroom_points', 'splashground_data', 'splashground_points',
       'amenities_points', 'total_points', 'total_pct', 'park_benches',
       'state', 'pop2020', 'pop2010', 'area2020'],
      dtype='object')

To see information about a DataFrame and its content:

In [6]:
parks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746 entries, 0 to 745
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   year                       746 non-null    int64
 1   rank                       746 non-null    int64
 2   city                       746 non-null    object
 3   med_park_size_data         746 non-null    float64
 4   med_park_size_points       746 non-null    float64
 5   park_pct_city_data         746 non-null    object
 6   park_pct_city_points       746 non-null    float64
 7   pct_near_park_data         746 non-null    object
 8   pct_near_park_points       746 non-null    float64
 9   spend_per_resident_data    746 non-null    object
 10  spend_per_resident_points  746 non-null    float64
 11  basketball_data            589 non-null    float64
 12  basketball_points          589 non-null    float64
 13  dogpark_data               589 non-null    float64
 14  dogpark_points             589 non-null    float64
 15  playground_data            746 non-null    float64
 16  playground_points          746 non-null    float64
 17  rec_sr_data                589 non-null    float64
 18  rec_sr_points              589 non-null    float64
 19  restroom_data              304 non-null    float64
 20  restroom_points            304 non-null    float64
 21  splashground_data          304 non-null    float64
 22  splashground_points        304 non-null    float64
 23  amenities_points           589 non-null    float64
 24  total_points               582 non-null    float64
 25  total_pct                  642 non-null    float64
 26  park_benches               442 non-null    float64
 27  state                      746 non-null    object
 28  pop2020                    739 non-null    float64
 29  pop2010                    739 non-null    float64
 30  area2020                   739 non-null    float64
dtypes: float64(24), int64(2), object(5)
memory usage: 180.8+ KB

To get some summary statistics about the values of a DataFrame:

In [7]:
parks.describe()

,year,rank,med_park_size_data,med_park_size_points,park_pct_city_points,pct_near_park_points,spend_per_resident_points,basketball_data,basketball_points,dogpark_data,...,restroom_points,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,pop2020,pop2010,area2020
count,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,589.000000,589.000000,589.000000,...,304.000000,304.000000,304.000000,589.000000,582.000000,642.000000,442.000000,7.390000e+02,7.390000e+02,739.000000
mean,2016.652815,42.702413,5.950737,14.936327,14.276139,32.327078,22.907507,3.377419,24.953311,1.298472,...,41.246711,1.891447,39.253289,28.896435,83.236254,52.581153,2.822398,7.207265e+05,6.654667e+05,188.967253
std,2.371271,26.759529,3.590357,11.507116,11.276906,22.361421,24.590379,2.599630,26.180219,1.169081,...,29.604238,2.267679,34.093421,20.811183,69.061782,14.192701,0.980314,1.065547e+06,9.986066e+05,203.289762
min,2012.000000,1.000000,0.600000,1.000000,1.000000,1.000000,1.000000,0.700000,1.000000,0.000000,...,1.000000,0.000000,0.000000,2.000000,3.000000,21.500000,0.500000,1.164480e+05,1.037010e+05,14.700000
25%,2015.000000,20.000000,3.300000,7.000000,6.000000,16.250000,7.000000,1.900000,7.000000,0.600000,...,18.000000,0.500000,11.000000,11.000000,45.000000,41.500000,2.000000,3.015780e+05,2.696660e+05,67.000000
50%,2017.000000,40.000000,5.130000,12.250000,11.000000,28.000000,14.000000,2.700000,15.000000,0.900000,...,33.500000,1.100000,30.000000,22.000000,63.250000,50.100000,2.500000,4.667420e+05,4.089580e+05,133.500000
75%,2019.000000,63.000000,7.800000,20.000000,20.000000,39.000000,27.000000,4.000000,33.000000,1.600000,...,64.250000,2.200000,59.000000,44.600000,92.000000,63.500000,3.500000,6.810540e+05,6.175940e+05,241.000000
max,2020.000000,98.000000,19.900000,50.000000,50.000000,100.000000,100.000000,28.300000,100.000000,7.200000,...,100.000000,10.600000,100.000000,92.500000,341.000000,86.500000,5.000000,8.804190e+06,8.175133e+06,1706.800000

To see the data types of a DataFrame:

In [8]:
parks.dtypes

year                           int64
rank                           int64
city                          object
med_park_size_data           float64
med_park_size_points         float64
park_pct_city_data            object
park_pct_city_points         float64
pct_near_park_data            object
pct_near_park_points         float64
spend_per_resident_data       object
spend_per_resident_points    float64
basketball_data              float64
basketball_points            float64
dogpark_data                 float64
dogpark_points               float64
playground_data              float64
playground_points            float64
rec_sr_data                  float64
rec_sr_points                float64
restroom_data                float64
restroom_points              float64
splashground_data            float64
splashground_points          float64
amenities_points             float64
total_points                 float64
total_pct                    float64
park_benches                 float64
state                         object
pop2020                      float64
pop2010                      float64
area2020                     float64
dtype: object

## Data Types

### Built-In Python

Python has built-in objects for handling different types of data, including
numeric and non numeric data.

Numeric data can be represented as either an `int` (integer) or `float` object.
An integer is simply a whole number, such as 0, 3, 3000...
When we assign as whole number to a variable, Python will use the int class:

In [9]:
a = 4

We can see the type of an object in Python using the `type` function:

In [10]:
type(a)

int

We can also explicitly construct an int object in Python:

In [11]:
b = int(4)

Integer objects don't allow for decimal points:

In [12]:
b = int(4.5)
b

4

A float (floating point number) stores numeric data with decimal precision:

In [13]:
a = 4.7
type(a)

float

Python supports using arithmetic operators on different numeric types by 
automatically altering the more limited type to match. For example:

In [14]:
a = 4.7
b = 3
c = a + b
type(c)

float

Additionally, if you divide an integer with another integer in Python, you will
get a float:

In [15]:
c = 4 / 4
type(c)

float

`bool` short for Boolean is a data type that stores either True or False. 
Booleans are used as values for expressions with yes-or-no responses.
For example:

In [16]:
True

True

In [17]:
type(True)

bool

In Python, text is stored in a String object called `str`. Strings are created
by enclosing a series of characters in quotes, either single or double quotes
can be used.

In [18]:
d = "hello world!"
type(d)

str

To convert between data types in Python, we use the constructor associated
with each type:

In [19]:
a = float(3)

Another example:

In [20]:
a = str(3)

### Comparison Operators

Comparison operators are extremely common in many programming tasks.
They allow for comparing between two values.
The operators are:
- `<` for "less than"
- `>` for "greater than"
- `<=` for "less than or equal to"
- `>=` for "greater than or equal to"
- `==` for "equal to"
- `!=` for "not equal to"

Notice that the "equal to" operator is two equal signs, this is to distinguish
it from the assignment operator.

Comparison operators return boolean values:

In [21]:
5 > 2

True

In [22]:
3 == 2

False

In [23]:
3 == "three"

False

In [24]:
3 != "three"

True

### In Pandas

Python's built-in data types are very flexible at the cost of specificity. 
NumPy provides more control to the programmer by adding many classes for
storing numeric data that can be modified to best match the data, in order
to improve memory and time performance.

Pandas, which is built on top of NumPy, incorporates these types and some of
its own.

These include:
- boolean
- int
- float
- complex
- datetime
- timedelta
- StringDtype
- python object (including strings)

For `int` and `float` data, in Pandas we can specify the number the size of
the int or float, such as int64 -> a 64 bit integer.

This number refers specifically to the number of bits that are used to store
the data. 64 bit integers can hold values between -9,223,372,036,854,775,808 and
9,223,372,036,854,775,807. Whereas a 16 bit integer can hold values between
-32,768 and 32,767. Floating point numbers store the number, as well as the values
after the decimal point. 

## Series

Each column in the DataFrame is a Pandas `Series` object.
A Series is a collection of values that all share the same data type. 
In addition, each value has a label, these labels don't need to be unique
and by default are integers starting at 0.

It is built on top of the NumPy ndarray object, and as such, will
perform much faster than the list object for numerical operations.

Lets look at the year column of our data. We can access it with the following:

In [25]:
year = parks["year"].copy()

In this case, we have assigned a copy of the year column from the parks 
dataframe to a variable we call year. If we didn't use the copy method,
then modifications we made to year, would also modify that column
in the DataFrame. This way, we can make changes without effecting
the original.

As with DataFrames, there are several functions for exploring series.

To get the first values, we can once again use `head`:

In [26]:
year.head()

0    2020
1    2020
2    2020
3    2020
4    2020
Name: year, dtype: int64

And again, to get the last values we can use `tail`:

In [27]:
year.tail()

741    2012
742    2012
743    2012
744    2012
745    2012
Name: year, dtype: int64

Since the data is numeric we can also get some summary data:

In [28]:
year.describe()

count     746.000000
mean     2016.652815
std         2.371271
min      2012.000000
25%      2015.000000
50%      2017.000000
75%      2019.000000
max      2020.000000
Name: year, dtype: float64

To see just the unique set of values we can use the `unique` method:

In [29]:
year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012])

Another very useful summary is `value_counts`:

In [30]:
year.value_counts()

2017    104
2016    103
2018    102
2020    101
2019    101
2015     78
2014     63
2013     52
2012     42
Name: year, dtype: int64

Series are powerful because we can apply operations on them in an element wise
fashion very easily and efficiently. For example:

In [31]:
year + 10

0      2030
1      2030
2      2030
3      2030
4      2030
       ...
741    2022
742    2022
743    2022
744    2022
745    2022
Name: year, Length: 746, dtype: int64

In addition, we can also use comparison operators:

In [32]:
year > 2014

0       True
1       True
2       True
3       True
4       True
       ...
741    False
742    False
743    False
744    False
745    False
Name: year, Length: 746, dtype: bool

### Indexing Series

There are three main methods for accessing specific values in Pandas:
1. by integer position
2. by label/name
3. based on a boolean array

These methods apply to Series, and as we will see later, to DataFrames.

### Selecting Values By Integer Position

To access elements in a Series by integer position, use the `iloc` attribute:

In [33]:
year.iloc[33]

2020

We can also pass a list or array of integer locations:

In [34]:
year.iloc[[33,0,23]]

33    2020
0     2020
23    2020
Name: year, dtype: int64

As with lists, we can use Python's slice operator:

In [35]:
year.iloc[3:10]

3    2020
4    2020
5    2020
6    2020
7    2020
8    2020
9    2020
Name: year, dtype: int64

### Selecting Values By Label

A Series in Pandas has labels attached to each value, in what Pandas calls
the index. 
We can see the index of a Series with the `index` attribute:

In [36]:
year.index

RangeIndex(start=0, stop=746, step=1)

Here we see that the index the index is a collection of integers. 
We can change that to something a little more descriptive.

In [37]:
year.index = parks["city"]
year.index

Index(['Minneapolis', 'Washington', 'St. Paul', 'Arlington', 'Cincinnati',
       'Portland', 'Irvine', 'San Francisco', 'Boston', 'Chicago',
       ...
       'Tucson', 'Memphis', 'Oklahoma City', 'Jacksonville', 'San Antonio',
       'Indianapolis', 'Mesa', 'Louisville', 'Charlotte', 'Fresno'],
      dtype='object', name='city', length=746)

To access elements based on label or name, we use the `loc` attribute:

In [38]:
year.loc["St. Paul"]

city
St. Paul    2020
St. Paul    2019
St. Paul    2018
St. Paul    2017
St. Paul    2016
St. Paul    2015
Name: year, dtype: int64

Notice that there were multiple values that matched with that label, so the
Series returned all of them.

We can also pass a list or array of labels:

In [39]:
year.loc[["St. Paul", "Mesa", "Fresno"]]

city
St. Paul    2020
St. Paul    2019
St. Paul    2018
St. Paul    2017
St. Paul    2016
St. Paul    2015
Mesa        2020
Mesa        2019
Mesa        2018
Mesa        2017
Mesa        2016
Mesa        2015
Mesa        2014
Mesa        2013
Mesa        2012
Fresno      2020
Fresno      2019
Fresno      2018
Fresno      2017
Fresno      2016
Fresno      2015
Fresno      2014
Fresno      2013
Fresno      2012
Name: year, dtype: int64

Additionally, Pandas supports the more conventional `[]` operator, directly
on Series.
We can pass labels to this operator:

In [40]:
year[["Irvine", "San Diego"]]

city
Irvine       2020
Irvine       2019
Irvine       2018
Irvine       2017
Irvine       2016
San Diego    2020
San Diego    2019
San Diego    2018
San Diego    2017
San Diego    2016
San Diego    2015
San Diego    2014
San Diego    2013
San Diego    2012
Name: year, dtype: int64

### Selecting Values Based On A Boolean Array

The third way to select values is based on a Boolean array. 
The Boolean array must have the same length as the number of elements
in the Series.

This is a really powerful method, that ties in well with functions that 
create Boolean Series.

For example, with the example from earlier:

In [41]:
year.loc[year > 2014]

city
Minneapolis      2020
Washington       2020
St. Paul         2020
Arlington        2020
Cincinnati       2020
                 ...
Oklahoma City    2015
Louisville       2015
Indianapolis     2015
Charlotte        2015
Fresno           2015
Name: year, Length: 589, dtype: int64

The `[]` operator also accepts Boolean Series:

In [42]:
year[year > 2014]

city
Minneapolis      2020
Washington       2020
St. Paul         2020
Arlington        2020
Cincinnati       2020
                 ...
Oklahoma City    2015
Louisville       2015
Indianapolis     2015
Charlotte        2015
Fresno           2015
Name: year, Length: 589, dtype: int64

## Indexing DataFrames

Conceptually, indexing DataFrames is very similar to the operations on Series. 
However, whereas Series are one dimensional, DataFrames are two dimensional.
A DataFrame is a collection of Series, organized as columns.

As with Series, we can use `iloc` to select rows based on their integer 
position:

In [43]:
parks.iloc[[300, 200, -1]]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
300,2018,94,Fresno,2.2,4.0,4%,3.0,62%,19.0,$42,...,1.0,15.0,19.0,50.0,30.9,NaN,California,542107.0,494665.0,115.2
200,2019,95,Charlotte/Mecklenburg County,16.5,50.0,6%,12.5,36%,7.5,$48,...,0.7,25.0,27.9,NaN,28.9,NaN,North Carolina,NaN,NaN,NaN
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

And we can use `loc` to select based on label, in this case the label is 
also integers:

In [44]:
parks.loc[732]

year                             2012
rank                               27
city                         Columbus
med_park_size_data                6.6
med_park_size_points             13.0
park_pct_city_data               8.1%
park_pct_city_points              8.0
pct_near_park_data                49%
pct_near_park_points             16.0
spend_per_resident_data        $68.94
spend_per_resident_points         6.0
basketball_data                   NaN
basketball_points                 NaN
dogpark_data                      NaN
dogpark_points                    NaN
playground_data                   1.9
playground_points                 7.0
rec_sr_data                       NaN
rec_sr_points                     NaN
restroom_data                     NaN
restroom_points                   NaN
splashground_data                 NaN
splashground_points               NaN
amenities_points                  NaN
total_points                     50.0
total_pct                        41.5
park_benches                      2.0
state                            Ohio
pop2020                      905748.0
pop2010                      787033.0
area2020                        220.0
Name: 732, dtype: object

Again, as with Series, we can use boolean arrays or lists to index:

In [45]:
parks.loc[parks["state"] == "California"]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
6,2020,7,Irvine,6.1,28.0,27%,50.0,82%,73.0,$215,...,0.7,25.0,67.3,318.0,79.6,NaN,California,307670.0,212375.0,65.6
7,2020,8,San Francisco,1.3,4.0,21%,50.0,100%,100.0,$399,...,1.0,36.0,61.7,316.0,78.9,NaN,California,873965.0,805235.0,46.9
17,2020,18,San Diego,6.8,32.0,19%,50.0,81%,71.0,$153,...,0.1,2.0,37.2,276.0,69.0,NaN,California,1386932.0,1307402.0,325.9
22,2020,23,Long Beach,3.2,14.0,10%,25.0,84%,76.0,$180,...,0.2,4.0,50.0,265.0,66.3,NaN,California,466742.0,462257.0,50.7
30,2020,30,Sacramento,5.4,25.0,9%,21.0,83%,75.0,$122,...,4.5,100.0,60.2,248.0,62.0,NaN,California,524943.0,466488.0,98.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2012,8,San Diego,6.7,14.0,22.8%,20.0,75%,28.0,$121.47,...,NaN,NaN,NaN,81.0,67.5,4.0,California,1386932.0,1307402.0,325.9
715,2012,12,San Jose,3.7,8.0,14.1%,15.0,69%,26.0,$135.68,...,NaN,NaN,NaN,76.0,63.5,3.5,California,1013240.0,945942.0,178.3
723,2012,19,Long Beach,3.2,7.0,10.3%,11.0,70%,26.0,$130.54,...,NaN,NaN,NaN,62.0,51.5,2.5,California,466742.0,462257.0,50.7
729,2012,25,Los Angeles,6.7,14.0,14.1%,15.0,52%,18.0,$55.14,...,NaN,NaN,NaN,52.0,43.5,2.0,California,3898747.0,3792621.0,469.5
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

This also works with just the `[]` operator:

In [46]:
parks[parks["state"] == "California"]

,year,rank,city,med_park_size_data,med_park_size_points,park_pct_city_data,park_pct_city_points,pct_near_park_data,pct_near_park_points,spend_per_resident_data,...,splashground_data,splashground_points,amenities_points,total_points,total_pct,park_benches,state,pop2020,pop2010,area2020
6,2020,7,Irvine,6.1,28.0,27%,50.0,82%,73.0,$215,...,0.7,25.0,67.3,318.0,79.6,NaN,California,307670.0,212375.0,65.6
7,2020,8,San Francisco,1.3,4.0,21%,50.0,100%,100.0,$399,...,1.0,36.0,61.7,316.0,78.9,NaN,California,873965.0,805235.0,46.9
17,2020,18,San Diego,6.8,32.0,19%,50.0,81%,71.0,$153,...,0.1,2.0,37.2,276.0,69.0,NaN,California,1386932.0,1307402.0,325.9
22,2020,23,Long Beach,3.2,14.0,10%,25.0,84%,76.0,$180,...,0.2,4.0,50.0,265.0,66.3,NaN,California,466742.0,462257.0,50.7
30,2020,30,Sacramento,5.4,25.0,9%,21.0,83%,75.0,$122,...,4.5,100.0,60.2,248.0,62.0,NaN,California,524943.0,466488.0,98.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2012,8,San Diego,6.7,14.0,22.8%,20.0,75%,28.0,$121.47,...,NaN,NaN,NaN,81.0,67.5,4.0,California,1386932.0,1307402.0,325.9
715,2012,12,San Jose,3.7,8.0,14.1%,15.0,69%,26.0,$135.68,...,NaN,NaN,NaN,76.0,63.5,3.5,California,1013240.0,945942.0,178.3
723,2012,19,Long Beach,3.2,7.0,10.3%,11.0,70%,26.0,$130.54,...,NaN,NaN,NaN,62.0,51.5,2.5,California,466742.0,462257.0,50.7
729,2012,25,Los Angeles,6.7,14.0,14.1%,15.0,52%,18.0,$55.14,...,NaN,NaN,NaN,52.0,43.5,2.0,California,3898747.0,3792621.0,469.5
745,2012,40,Fresno,4.9,10.0,2.1%,1.0,35%,8.0,$54.98,...,NaN,NaN,NaN,26.0,21.5,0.5,California,542107.0,494665.0,115.2

To access columns from a DataFrame, we use the `[]` operator, as we have 
already seen:

In [47]:
parks["pop2020"]

0      429954.0
1      689545.0
2      311527.0
3           NaN
4      309317.0
         ...
741    887642.0
742    504258.0
743    633045.0
744    874579.0
745    542107.0
Name: pop2020, Length: 746, dtype: float64

We can also pass a list of column names, in any order:

In [48]:
parks[["pop2020", "city"]]

      pop2020          city
0    429954.0   Minneapolis
1    689545.0    Washington
2    311527.0      St. Paul
3         NaN     Arlington
4    309317.0    Cincinnati
..        ...           ...
741  887642.0  Indianapolis
742  504258.0          Mesa
743  633045.0    Louisville
744  874579.0     Charlotte
745  542107.0        Fresno

[746 rows x 2 columns]

If we select a single column from the DataFrame, we get a Series, 
which we can index as we saw before:

In [49]:
parks["pop2020"].iloc[1:10]

1     689545.0
2     311527.0
3          NaN
4     309317.0
5     652503.0
6     307670.0
7     873965.0
8     675647.0
9    2746388.0
Name: pop2020, dtype: float64

So, to combine with what we saw before with boolean indexing:

In [50]:
parks[["city", "pop2020"]].loc[parks["state"] == "California"]

              city    pop2020
6           Irvine   307670.0
7    San Francisco   873965.0
17       San Diego  1386932.0
22      Long Beach   466742.0
30      Sacramento   524943.0
..             ...        ...
711      San Diego  1386932.0
715       San Jose  1013240.0
723     Long Beach   466742.0
729    Los Angeles  3898747.0
745         Fresno   542107.0

[129 rows x 2 columns]

A more elegant approach to the above is to use:

In [51]:
parks.loc[parks["state"] == "California", ["city", "pop2020"]]

              city    pop2020
6           Irvine   307670.0
7    San Francisco   873965.0
17       San Diego  1386932.0
22      Long Beach   466742.0
30      Sacramento   524943.0
..             ...        ...
711      San Diego  1386932.0
715       San Jose  1013240.0
723     Long Beach   466742.0
729    Los Angeles  3898747.0
745         Fresno   542107.0

[129 rows x 2 columns]

## Special Values

Often times, the data we have will work with has missing, or invalid data.
Its important to understand these values, and how to work with them in Pandas.

There are many reasons that could cause these values to be missing or incomplete,
and as a result, Pandas provides lots of flexibility for detecting and handling
these values.

In Pandas, these special values, are generally treated as missing values
in the dataset, and are represented by the NumPy `nan` type. This reduces
some of the nuance of data values and types, but was seemingly done
for computational preformance reasons.

### Types of Values Considered Missing by Pandas

In addition to `np.nan` (which displays as NaN), Pandas interprets 
several other values as missing. 
This includes Python's `None` type, as well as Pandas' experimental `NA` types.

Python's `None` type represents something that has no value. 
It often comes about as the return of a function, if something hasn't
been defined yet, or if something wasn't found.

When creating a Series, we can pass this value:

In [52]:
pd.Series([None, "one", "two"])

0    None
1     one
2     two
dtype: object

Be aware that `None` is a Python object, and in the above example, the 
datatype of the series became 'object'. If we specify a datatype explicitly
then Pandas will convert it to one of its representations:

In [53]:
pd.Series([1.5,2.0,3, None], dtype="float")

0    1.5
1    2.0
2    3.0
3    NaN
dtype: float64

Be aware that `None` is a Python object, and in the above example, the 
datatype of the series became 'object'. If we specify a datatype explicitly
then Pandas will convert it to one of its representations:

In [54]:
pd.Series(["the", "and", None], dtype="string")

0     the
1     and
2    <NA>
dtype: string

### Reading in Missing Values from a CSV file

An obvious source of missing or incomplete values is the data itself. 
When the data was collected, there may have been reasons to code missing data.
For example, in collection of survey responses, there may be times where the 
answer was not applicable. 
Another example would be if a measurement was not taken on some of the samples. 
Obviously, there are no rules on how this was represented in the data set. 
However there are several conventions, and Pandas is aware of many of them. 

When reading data from a CSV file, Pandas will automatically detect missing 
values. 
By default, it will convert any empty cell, or string such as 'na', 'nan', 'null',
'N/A', and other variants to NaN.
A full list can be found in the Pandas documentation: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html


### Detecting Missing Values

To detect missing values, Pandas provides two complementary methods - 
`isna` and `notna`.

We can see information about missing values with the `count` method on 
DataFrames:

In [55]:
parks.count()

year                         746
rank                         746
city                         746
med_park_size_data           746
med_park_size_points         746
park_pct_city_data           746
park_pct_city_points         746
pct_near_park_data           746
pct_near_park_points         746
spend_per_resident_data      746
spend_per_resident_points    746
basketball_data              589
basketball_points            589
dogpark_data                 589
dogpark_points               589
playground_data              746
playground_points            746
rec_sr_data                  589
rec_sr_points                589
restroom_data                304
restroom_points              304
splashground_data            304
splashground_points          304
amenities_points             589
total_points                 582
total_pct                    642
park_benches                 442
state                        746
pop2020                      739
pop2010                      739
area2020                     739
dtype: int64

If we look at the `park_benches` columns of the DataFrame, we can see what 
those missing values look like.

In [56]:
pb = parks["park_benches"]
pb.count()

442

The return of `isna` is a boolean Series indicating which of the values 
are considered missing:

In [57]:
pb.isna()

0       True
1       True
2       True
3       True
4       True
       ...
741    False
742    False
743    False
744    False
745    False
Name: park_benches, Length: 746, dtype: bool

The reverse - to see which values are not considered missing - is returned 
with `notna`:

In [58]:
pb.notna()

0      False
1      False
2      False
3      False
4      False
       ...
741     True
742     True
743     True
744     True
745     True
Name: park_benches, Length: 746, dtype: bool

### Replacing Missing Values

We can use this boolean Series to subset. 
For example, to keep only the values that aren't missing:

In [59]:
pb.loc[pb.notna()]

304    5.0
305    5.0
306    5.0
307    4.5
308    4.5
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 442, dtype: float64

Pandas also provides a shortcut with the `dropna` method:

In [60]:
pb.dropna()

304    5.0
305    5.0
306    5.0
307    4.5
308    4.5
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 442, dtype: float64

Another strategy may be to fill the missing values. We could do so using the 
`fillna` method:

In [61]:
pb.fillna(-1)

0     -1.0
1     -1.0
2     -1.0
3     -1.0
4     -1.0
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 746, dtype: float64

Additionally, the data set may have its own indicator for missing values, 
e.g "" or 0. We can convert those to missing using the `replace` method:

In [62]:
pb.replace(-1, np.nan)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
741    1.5
742    1.5
743    1.0
744    1.0
745    0.5
Name: park_benches, Length: 746, dtype: float64